### PR TITLE
Add logos for expirements

### PR DESCRIPTION
**Pull request by eylonronen**
Issue #827 
Wasn't sure what "Track the icon" meant so added the icons to each expirement folder

### CODE REVIEW

**Comment by kmjayadeep** [comment]
Wrong issue it seems

**Comment by chandankumar4** [comment]
Thanks for your contribution @eylonronen, Can you raise the same PR for Repo (https://github.com/litmuschaos/charthub.litmuschaos.io),  and follow the directory structure mention in the issue: https://github.com/litmuschaos/litmus/issues/879, You can close this PR after raising the another one

**Comment by aditya109** [comment]
@eylonronen sorry we will will be able to take this icon as this icon has some copyright issues.

**Comment by inyee786** [comment]
@aditya109  do we need this pull request?

**Comment by ajeshbaby** [comment]
Closing this pull request due to inactivity.

**Pull request closed without merging**
