### PR TITLE
Add brazilian portuguese README translation

### LINKED ISSUE #2263: Translate README.md to Portuguese language

### PR DESCRIPTION
**Pull request by rafaeelaudibert**
Signed-off-by: RafaAudibert - Deepin <rafaeelaudibert@gmail.com>

## Proposed changes
Add PT-BR README translation
Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:
Closes #2263

### CODE REVIEW

**Review by ajeshbaby — APPROVED** [review]
LGTM

**Comment by tacoelho** [comment]
This has portuguese errors.

**Comment by rafaeelaudibert** [comment]
@tacoelho Cloud you please pinpoint them in the PR so that I can fix them? Thank you :D

**Comment by tacoelho** [comment]
> 
> 
> @tacoelho Cloud you please pinpoint them in the PR so that I can fix them? Thank you :D

I´m sorry but it seems that you just threw it at Google Translator. The overall translation is mechanic. 
If you want a proper translation @ajeshbaby I can do it.

**Comment by rafaeelaudibert** [comment]
I'm sorry @tacoelho but I can't agree with you, having thoroughly gone through the article as I have gone, translating it. You can easily check that it wasn't translated using Google Translate, by using it, and checking that the translation clearly doesn't match. If you have any specific point where you think I should take another look, and maybe, dispose of some extra time trying to improve the translation, everybody on the repo (including me) would be grateful.

**Review by ksatchit — APPROVED** [review]

**Pull request merged**
