### PR TITLE
Proposal: Load testing with k6

### PR DESCRIPTION
**Pull request by namkyu1999**
## Proposed changes

I propose a new Chaos Fault - Load Testing with k6. Please take a look at my documentation.

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Comment by Jonsy13** [comment]
Hi @namkyu1999 Thanks for the proposal, I have gone through it. It looks good to me.

**Just trying to understand -**
- It is like invoking a K6 script for doing chaos (like `stress-ng`)
- If we add it, it can open a door for users to write chaos experiments easily in terms of contribution or even BYOC in some terms.
- It is like our SSH Chaos Category where users can provide a JS script & mount it from configmap/secret & we run the chaos experiment.

**Comment by namkyu1999** [comment]
> * If we add it, it can open a door for users to write chaos experiments easily in terms of contribution or even BYOC in some terms.
> * It is like our SSH Chaos Category where users can provide a JS script & mount it from configmap/secret & we run the chaos experiment.

Exactly :)

**Comment by namkyu1999** [comment]
> Hi @namkyu1999 Thanks for the proposal, I have gone through it. It looks good to me.
> 
> **Just trying to understand -**
> 
> * It is like invoking a K6 script for doing chaos (like `stress-ng`)
> * If we add it, it can open a door for users to write chaos experiments easily in terms of contribution or even BYOC in some terms.
> * It is like our SSH Chaos Category where users can provide a JS script & mount it from configmap/secret & we run the chaos experiment.

Exactly :)

**Comment by uditgaurav** [comment]
Hi @namkyu1999, feel free to let me know if you need support or guidance on how to proceed.

**Review by ksatchit — APPROVED** [review]

**Pull request merged**
