### PR TITLE
fix: add handleListenEnter on Inputfield for listening enter

### PR DESCRIPTION
**Pull request by kala2**
## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Comment by A4k9** [comment]
Cloned and tested. Works Great! Thanks for the contribution :+1:

**Review by A4k9 — COMMENTED** [review]
Everything Worked great on my local Env. Please review and approve.

**Review by ishangupta-ds — APPROVED** [review]

**Review by amityt — APPROVED** [review]

**Comment by rajdas98** [comment]
Hi @kala2 , Can you resolve these merge conflicts?

**Comment by ishangupta-ds** [comment]
@kala2 there are some merge conflicts.

**Review by ishangupta-ds — CHANGES_REQUESTED** [review]
@kala2 there are merge conflicts

**Comment by rajdas98** [comment]
Hi @kala2, Thanks for this PR As part of the clean-up process, we are going to close this PR by the end of this week. Please Let me know if you want to work on this PR.

**Comment by rajdas98** [comment]
Hi @kala2, I am closing this PR. Just put a comment if you want to work on this, we can re-open this PR. Thanks.a

**Pull request closed without merging**
