### PR TITLE
chore(litmus-portal): Added Input Validation + Modified InputField + Updated Login

### PR DESCRIPTION
**Pull request by S-ayanide**
## Proposed changes

* Input Fields have been modified to resemble the design system (includes, focus, onHover, onSelected, onDisabled, etc)
* Welcome Modal Form Validation taken care of
* Created abstracted validation utility with validation functions like `Email Validation`, `Empty Text Validation`, `Only Alphabet Validation`, `Password Validation`, `Confirm Password Validation` and `Invalid Text Validation`
* Welcome Modal would not move forward if the user input is not validated -> this would also disable the **Continue** and **Let's Start** Buttons
* Upon successfully comparing the passwords if correct InputField would show success state (Turn green)
* Updated the theme to add disabled color
* Updated Login Page Design
* Username Validation updated in Login Page
* Password Validation intentionally skipped for Login Page since the current password doesn't fit the validation requirement

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [X] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [X] I have signed the commit for DCO to be passed.
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [X] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Review by arkajyotiMukherjee — APPROVED** [review]
LGTM

**Review by amityt — APPROVED** [review]

**Review by amityt — APPROVED** [review]

**Review by gdsoumya — APPROVED** [review]

**Review by arkajyotiMukherjee — APPROVED** [review]

**Review by rajdas98 — APPROVED** [review]

**Comment by rajdas98** [comment]
Thanks for this PR

**Pull request merged**
