### PR TITLE
(litmus-portal): Bug fixes and error handling related to analytics.

### PR DESCRIPTION
**Pull request by ishangupta-ds**
Signed-off-by: ishangupta-ds <ishan.gupta@mayadata.io>

## Proposed changes

This PR fixes bugs and adds error handlers for analytics.

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- None.

## Special notes for your reviewer:
High Priority bug-fix PR.

### CODE REVIEW

**Comment by ishangupta-ds** [comment]
@rajdas98 @A4k9 @Saranya-jena @oumkale @amityt @Jonsy13 PTAL.

**Review by Saranya-jena — APPROVED** [review]
LGTM

**Review by oumkale — APPROVED** [review]

**Comment by oumkale** [comment]
ci/circleci: docker-build-backend failed

**Comment by ishangupta-ds** [comment]
> ci/circleci: docker-build-backend failed

no backend changes are there in my PR.

**Review by SarthakJain26 — APPROVED** [review]
LGTM

**Pull request merged**
