### PR TITLE
(litmus-portal): Added time-series plots with minor redux update for integration.

### LINKED ISSUE #1607: Community Page Dev.
Community Page Development and a backend module for Litmus Portal using Plotly, Google Analytics and GitOps.

### PR DESCRIPTION
**Pull request by ishangupta-ds**
Signed-off-by: ishangupta-ds <ishan.gupta@mayadata.io>

What this PR does / why we need it:

Updated Redux, Model and Community Page. Added time series chart components for metrics.

Which issue this PR fixes:

fixes #1607 

**Checklist**

* [ ] Does this PR have a corresponding GitHub issue?
* [ ] Have you included relevant README for the chaoslib/experiment with details?
* [ ] Have you added debug messages where necessary? 
* [ ] Have you added task comments where necessary? 
* [ ] Have you tested the changes for possible failure conditions?
* [ ] Have you provided the positive & negative test logs for the litmusbook execution?
* [ ] Does the litmusbook ensure idempotency of cluster state?, i.e., is cluster restored to original state?
* [ ] Have you used non-shell/command modules for Kubernetes tasks?
* [ ] Have you (jinja) templatized custom scripts that is run by the litmusbook, if any? 
* [ ] Have you (jinja) templatized Kubernetes deployment manifests used by the litmusbook, if any?
* [ ] Have you reused/created util functions instead of repeating tasks in the litmusbook?
* [ ] Do the artifacts follow the appropriate directory structure? 
* [ ] Have you isolated storage (eg: OpenEBS) specific implementations, checks? 
* [ ] Have you isolated platform (eg: baremetal kubeadm/openshift/aws/gcloud) specific implementations, checks?  
* [ ] Are the ansible facts well defined? Is the scope explicitly set for playbook & included utils?
* [ ] Have you ensured minimum/careful usage of shell utilities (awk, grep, sed, cut, xargs etc.,)?
* [ ] Can the limtusbook be executed both from within & outside a container (configurable paths, no hardcode)?
* [ ] Can you suggest the minimal resource requirements for the litmusbook execution?
* [ ] Does the litmusbook job artifact carry comments/default options/range for the ENV tunables?
* [ ] Has the litmusbooks been linted? 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by gdsoumya** [comment]
> I think we should avoid sending in package-lock.json since it creates conflicts. It's okay for this PR but I think we should avoid it because this file is pretty long and resolving conflicts is totally unnecessary for this because we can regenerate it exactly with the number of dependencies we have.

@S-ayanide I disagree, package-lock.json is needed to maintain the versions throughout all the working repos. The package.json will automatically upgrade the version of the npm packages when someone does an `npm install` and it can break the whole project, this is where package-lock.json comes in and ensure the same dependency setup throughout all forks. We can maybe try making changes in the package.json to go for fixed versions but I don't think that's very maintainable.

**Comment by gdsoumya** [comment]
> You have created two separate components for TimeSeriesGrowth and Trend. Only the Time Series graph would be reusable later on so you can create only one component CommunityTimeSeries and have Trend and Growth plots inside of it.

That's what we suggested but there are some problems @ishangupta-ds is facing while doing that. We'll take a look t it after it get's merged.

**Comment by ishangupta-ds** [comment]
> You have created two separate components for TimeSeriesGrowth and Trend. Only the Time Series graph would be reusable later on so you can create only one component CommunityTimeSeries and have Trend and Growth plots inside of it.

It will be refactored soon.

**Comment by ishangupta-ds** [comment]
@rajdas98 can you preview this?

**Pull request merged**
