### PR TITLE
fixed ansible-runner dockerfile to reduce image size

### PR DESCRIPTION
**Pull request by kmjayadeep**
Signed-off-by: Jayadeep KM <kmjayadeep@gmail.com>

**What this PR does / why we need it**:

Optimizes the ansible-runner dockerfile to reduce image size from 627MB to just 298MB.

fixes litmuschaos/litmus#832

Changes:

- added tag - `bionic` to base image `ubuntu` (good practice)
- cleanup apt cache after installing dependencies
- added `--no-install-recommends` to apt install command to avoid installing optional dependencies
- added `python-setuptools` to apt-install command. (Earlier it was being installed along with optional dependencies. It is required for ansible setup)

With these minor changes the image size was reduced drastically.
I will run a full experiment with the new image and post the logs soon

**Checklist**

* [x] Does this PR have a corresponding GitHub issue?
* [ ] Have you included relevant README for the chaoslib/experiment with details?
* [ ] Have you added debug messages where necessary? 
* [ ] Have you added task comments where necessary? 
* [ ] Have you tested the changes for possible failure conditions?
* [ ] Have you provided the positive & negative test logs for the litmusbook execution?
* [ ] Does the litmusbook ensure idempotency of cluster state?, i.e., is cluster restored to original state?
* [ ] Have you used non-shell/command modules for Kubernetes tasks?
* [ ] Have you (jinja) templatized custom scripts that is run by the litmusbook, if any? 
* [ ] Have you (jinja) templatized Kubernetes deployment manifests used by the litmusbook, if any?
* [ ] Have you reused/created util functions instead of repeating tasks in the litmusbook?
* [ ] Do the artifacts follow the appropriate directory structure? 
* [ ] Have you isolated storage (eg: OpenEBS) specific implementations, checks? 
* [ ] Have you isolated platform (eg: baremetal kubeadm/openshift/aws/gcloud) specific implementations, checks?  
* [ ] Are the ansible facts well defined? Is the scope explicitly set for playbook & included utils?
* [ ] Have you ensured minimum/careful usage of shell utilities (awk, grep, sed, cut, xargs etc.,)?
* [ ] Can the limtusbook be executed both from within & outside a container (configurable paths, no hardcode)?
* [ ] Can you suggest the minimal resource requirements for the litmusbook execution?
* [ ] Does the litmusbook job artifact carry comments/default options/range for the ENV tunables?
* [ ] Has the litmusbooks been linted? 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by kmjayadeep** [comment]
Also fixes #588

**Comment by ksatchit** [comment]
Awesome! @kmjayadeep - this was a long pending technical debt. Can you confirm that you are able to run experiments successfully post these changes?

**Comment by kmjayadeep** [comment]
> Awesome! @kmjayadeep - this was a long pending technical debt. Can you confirm that you are able to run experiments successfully post these changes?

I'm looking into it. Will run and post logs by evening

**Comment by kmjayadeep** [comment]
@ksatchit 
Here is the log from `pod-delete` which is ran using the new image

```
ansible-playbook 2.7.3
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]
No config file found; using defaults
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
statically imported: /experiments/generic/pod_delete/pod_delete_ansible_prerequisites.yml

PLAYBOOK: pod_delete_ansible_logic.yml *****************************************
1 plays in ./experiments/generic/pod_delete/pod_delete_ansible_logic.yml

PLAY [localhost] ***************************************************************
2019-10-10T14:31:31.272060 (delta: 0.032407)         elapsed: 0.032407 ******** 
=============================================================================== 

TASK [Gathering Facts] *********************************************************
task path: /experiments/generic/pod_delete/pod_delete_ansible_logic.yml:2
2019-10-10T14:31:31.281063 (delta: 0.008973)         elapsed: 0.04141 ********* 
ok: [127.0.0.1]
META: ran handlers

TASK [Identify the chaos util to be invoked] ***********************************
task path: /experiments/generic/pod_delete/pod_delete_ansible_prerequisites.yml:1
2019-10-10T14:31:36.125229 (delta: 4.844138)         elapsed: 4.885576 ******** 
changed: [127.0.0.1] => {"changed": true, "checksum": "c272806e35212135d7ba563c282a0ab52a9d56a4", "dest": "./chaosutil.yml", "gid": 0, "group": "root", "md5sum": "d138cf6836284fb164fe8bdf4032cafc", "mode": "0644", "owner": "root", "size": 54, "src": "/root/.ansible/tmp/ansible-tmp-1570717896.15-180831474772323/source", "state": "file", "uid": 0}

TASK [include_vars] ************************************************************
task path: /experiments/generic/pod_delete/pod_delete_ansible_logic.yml:21
2019-10-10T14:31:36.546563 (delta: 0.421313)         elapsed: 5.30691 ********* 
ok: [127.0.0.1] => {"ansible_facts": {"c_util": "/chaoslib/litmus/pod_failure_by_litmus.yml"}, "ansible_included_var_files": ["/experiments/generic/pod_delete/chaosutil.yml"], "changed": false}

TASK [Construct chaos result name (experiment_name)] ***************************
task path: /experiments/generic/pod_delete/pod_delete_ansible_logic.yml:27
2019-10-10T14:31:36.600929 (delta: 0.054277)         elapsed: 5.361276 ******** 
ok: [127.0.0.1] => {"ansible_facts": {"c_experiment": "engine-nginx-pod-delete"}, "changed": false}

TASK [include_tasks] ***********************************************************
task path: /experiments/generic/pod_delete/pod_delete_ansible_logic.yml:34
2019-10-10T14:31:36.669696 (delta: 0.068733)         elapsed: 5.430043 ******** 
included: /utils/runtime/update_chaos_result_resource.yml for 127.0.0.1

TASK [Generate the litmus result CR to reflect SOT (Start of Test)] ************
task path: /utils/runtime/update_chaos_result_resource.yml:3
2019-10-10T14:31:36.745188 (delta: 0.075398)         elapsed: 5.505535 ******** 
changed: [127.0.0.1] => {"changed": true, "checksum": "762fa33f316adce43a6b17b938253877f285396a", "dest": "./chaos-result.yaml", "gid": 0, "group": "root", "md5sum": "16f40e6ba355987016c0dcb2d50b31dc", "mode": "0644", "owner": "root", "size": 342, "src": "/root/.ansible/tmp/ansible-tmp-1570717896.78-178101241777002/source", "state": "file", "uid": 0}

TASK [Apply the litmus result CR] **********************************************
task path: /utils/runtime/update_chaos_result_resource.yml:12
2019-10-10T14:31:36.986564 (delta: 0.24127)         elapsed: 5.746911 ********* 
changed: [127.0.0.1] => {"changed": true, "cmd": "kubectl apply -f chaos-result.yaml -n litmus", "delta": "0:00:00.834665", "end": "2019-10-10 14:31:38.031345", "failed_when_result": false, "rc": 0, "start": "2019-10-10 14:31:37.196680", "stderr": "", "stderr_lines": [], "stdout": "chaosresult.litmuschaos.io/engine-nginx-pod-delete created", "stdout_lines": ["chaosresult.litmuschaos.io/engine-nginx-pod-delete created"]}

TASK [Update the litmus result CR to reflect EOT (End of Test)] ****************
task path: /utils/runtime/update_chaos_result_resource.yml:22
2019-10-10T14:31:38.087055 (delta: 1.10046)         elapsed: 6.847402 ********* 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Apply the litmus result CR] **********************************************
task path: /utils/runtime/update_chaos_result_resource.yml:31
2019-10-10T14:31:38.136998 (delta: 0.0499)         elapsed: 6.897345 ********** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Verify that the AUT (Application Under Test) is running] *****************
task path: /experiments/generic/pod_delete/pod_delete_ansible_logic.yml:41
2019-10-10T14:31:38.182087 (delta: 0.04503)         elapsed: 6.942434 ********* 
included: /utils/common/status_app_pod.yml for 127.0.0.1

TASK [Get the container status of application.] ********************************
task path: /utils/common/status_app_pod.yml:2
2019-10-10T14:31:38.254200 (delta: 0.072072)         elapsed: 7.014547 ******** 
changed: [127.0.0.1] => {"attempts": 1, "changed": true, "cmd": "kubectl get pod -n litmus -l run=\"myserver\" -o custom-columns=:..containerStatuses[].state --no-headers | grep -w \"running\"", "delta": "0:00:00.465507", "end": "2019-10-10 14:31:38.849731", "rc": 0, "start": "2019-10-10 14:31:38.384224", "stderr": "", "stderr_lines": [], "stdout": "map[running:map[startedAt:2019-10-10T14:30:46Z]]", "stdout_lines": ["map[running:map[startedAt:2019-10-10T14:30:46Z]]"]}

TASK [Checking {{ application_name }} pod is in running state] *****************
task path: /utils/common/status_app_pod.yml:13
2019-10-10T14:31:38.905819 (delta: 0.651584)         elapsed: 7.666166 ******** 
changed: [127.0.0.1] => {"attempts": 1, "changed": true, "cmd": "kubectl get pods -n litmus -o jsonpath='{.items[?(@.metadata.labels.run==\"myserver\")].status.phase}'", "delta": "0:00:00.464719", "end": "2019-10-10 14:31:39.507914", "rc": 0, "start": "2019-10-10 14:31:39.043195", "stderr": "", "stderr_lines": [], "stdout": "Running", "stdout_lines": ["Running"]}

TASK [include_tasks] ***********************************************************
task path: /experiments/generic/pod_delete/pod_delete_ansible_logic.yml:52
2019-10-10T14:31:39.555676 (delta: 0.649822)         elapsed: 8.316023 ******** 
included: /chaoslib/litmus/pod_failure_by_litmus.yml for 127.0.0.1

TASK [Derive chaos iterations] *************************************************
task path: /chaoslib/litmus/pod_failure_by_litmus.yml:1
2019-10-10T14:31:39.625542 (delta: 0.069835)         elapsed: 8.385889 ******** 
ok: [127.0.0.1] => {"ansible_facts": {"chaos_iterations": "3"}, "changed": false}

TASK [Set min chaos count to 1 if interval > duration] *************************
task path: /chaoslib/litmus/pod_failure_by_litmus.yml:5
2019-10-10T14:31:39.684111 (delta: 0.058539)         elapsed: 8.444458 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Kill application pods randomly for the specified duration] ***************
task path: /chaoslib/litmus/pod_failure_by_litmus.yml:10
2019-10-10T14:31:39.721339 (delta: 0.037192)         elapsed: 8.481686 ******** 
skipping: [127.0.0.1] => (item=1)  => {"changed": false, "item": "1", "skip_reason": "Conditional result was False"}
skipping: [127.0.0.1] => (item=2)  => {"changed": false, "item": "2", "skip_reason": "Conditional result was False"}
skipping: [127.0.0.1] => (item=3)  => {"changed": false, "item": "3", "skip_reason": "Conditional result was False"}

TASK [Kill application pods randomly for the specified duration] ***************
task path: /chaoslib/litmus/pod_failure_by_litmus.yml:20
2019-10-10T14:31:39.789518 (delta: 0.068149)         elapsed: 8.549865 ******** 
changed: [127.0.0.1] => (item=1) => {"changed": true, "cmd": "kubectl get pods -l run=myserver -n litmus --no-headers -o custom-columns=:metadata.name | shuf -n 1 | xargs kubectl delete pod -n litmus\n sleep 5", "delta": "0:00:07.570562", "end": "2019-10-10 14:31:47.508054", "item": "1", "rc": 0, "start": "2019-10-10 14:31:39.937492", "stderr": "", "stderr_lines": [], "stdout": "pod \"myserver-54c896dd7b-lfcrs\" deleted", "stdout_lines": ["pod \"myserver-54c896dd7b-lfcrs\" deleted"]}
changed: [127.0.0.1] => (item=2) => {"changed": true, "cmd": "kubectl get pods -l run=myserver -n litmus --no-headers -o custom-columns=:metadata.name | shuf -n 1 | xargs kubectl delete pod -n litmus\n sleep 5", "delta": "0:00:15.148389", "end": "2019-10-10 14:32:02.756118", "item": "2", "rc": 0, "start": "2019-10-10 14:31:47.607729", "stderr": "", "stderr_lines": [], "stdout": "pod \"myserver-54c896dd7b-hnb52\" deleted", "stdout_lines": ["pod \"myserver-54c896dd7b-hnb52\" deleted"]}
changed: [127.0.0.1] => (item=3) => {"changed": true, "cmd": "kubectl get pods -l run=myserver -n litmus --no-headers -o custom-columns=:metadata.name | shuf -n 1 | xargs kubectl delete pod -n litmus\n sleep 5", "delta": "0:00:09.892644", "end": "2019-10-10 14:32:12.764518", "item": "3", "rc": 0, "start": "2019-10-10 14:32:02.871874", "stderr": "", "stderr_lines": [], "stdout": "pod \"myserver-54c896dd7b-55dg8\" deleted", "stdout_lines": ["pod \"myserver-54c896dd7b-55dg8\" deleted"]}

TASK [Verify AUT liveness post fault-injection] ********************************
task path: /experiments/generic/pod_delete/pod_delete_ansible_logic.yml:58
2019-10-10T14:32:12.816159 (delta: 33.026607)         elapsed: 41.576506 ****** 
included: /utils/common/status_app_pod.yml for 127.0.0.1

TASK [Get the container status of application.] ********************************
task path: /utils/common/status_app_pod.yml:2
2019-10-10T14:32:12.899939 (delta: 0.083743)         elapsed: 41.660286 ******* 
changed: [127.0.0.1] => {"attempts": 1, "changed": true, "cmd": "kubectl get pod -n litmus -l run=\"myserver\" -o custom-columns=:..containerStatuses[].state --no-headers | grep -w \"running\"", "delta": "0:00:00.457167", "end": "2019-10-10 14:32:13.492276", "rc": 0, "start": "2019-10-10 14:32:13.035109", "stderr": "", "stderr_lines": [], "stdout": "map[running:map[startedAt:2019-10-10T14:32:09Z]]", "stdout_lines": ["map[running:map[startedAt:2019-10-10T14:32:09Z]]"]}

TASK [Checking {{ application_name }} pod is in running state] *****************
task path: /utils/common/status_app_pod.yml:13
2019-10-10T14:32:13.544018 (delta: 0.644051)         elapsed: 42.304365 ******* 
changed: [127.0.0.1] => {"attempts": 1, "changed": true, "cmd": "kubectl get pods -n litmus -o jsonpath='{.items[?(@.metadata.labels.run==\"myserver\")].status.phase}'", "delta": "0:00:00.434568", "end": "2019-10-10 14:32:14.106480", "rc": 0, "start": "2019-10-10 14:32:13.671912", "stderr": "", "stderr_lines": [], "stdout": "Running", "stdout_lines": ["Running"]}

TASK [set_fact] ****************************************************************
task path: /experiments/generic/pod_delete/pod_delete_ansible_logic.yml:67
2019-10-10T14:32:14.155817 (delta: 0.611768)         elapsed: 42.916164 ******* 
ok: [127.0.0.1] => {"ansible_facts": {"flag": "pass"}, "changed": false}

TASK [include_tasks] ***********************************************************
task path: /experiments/generic/pod_delete/pod_delete_ansible_logic.yml:77
2019-10-10T14:32:14.218250 (delta: 0.062331)         elapsed: 42.978597 ******* 
included: /utils/runtime/update_chaos_result_resource.yml for 127.0.0.1

TASK [Generate the litmus result CR to reflect SOT (Start of Test)] ************
task path: /utils/runtime/update_chaos_result_resource.yml:3
2019-10-10T14:32:14.288352 (delta: 0.070068)         elapsed: 43.048699 ******* 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Apply the litmus result CR] **********************************************
task path: /utils/runtime/update_chaos_result_resource.yml:12
2019-10-10T14:32:14.328276 (delta: 0.039891)         elapsed: 43.088623 ******* 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Update the litmus result CR to reflect EOT (End of Test)] ****************
task path: /utils/runtime/update_chaos_result_resource.yml:22
2019-10-10T14:32:14.365674 (delta: 0.037368)         elapsed: 43.126021 ******* 
changed: [127.0.0.1] => {"changed": true, "checksum": "7bd582f3deb9392050eef348952bd8ab5c04664b", "dest": "./chaos-result.yaml", "gid": 0, "group": "root", "md5sum": "0e766db40cb0d0418c002f63e27d264b", "mode": "0644", "owner": "root", "size": 339, "src": "/root/.ansible/tmp/ansible-tmp-1570717934.4-225032957175293/source", "state": "file", "uid": 0}

TASK [Apply the litmus result CR] **********************************************
task path: /utils/runtime/update_chaos_result_resource.yml:31
2019-10-10T14:32:15.015535 (delta: 0.64983)         elapsed: 43.775882 ******** 
changed: [127.0.0.1] => {"changed": true, "cmd": "kubectl apply -f chaos-result.yaml -n litmus", "delta": "0:00:00.496585", "end": "2019-10-10 14:32:15.628181", "failed_when_result": false, "rc": 0, "start": "2019-10-10 14:32:15.131596", "stderr": "", "stderr_lines": [], "stdout": "chaosresult.litmuschaos.io/engine-nginx-pod-delete configured", "stdout_lines": ["chaosresult.litmuschaos.io/engine-nginx-pod-delete configured"]}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=20   changed=10   unreachable=0    failed=0   

2019-10-10T14:32:15.655633 (delta: 0.64006)         elapsed: 44.41598 ********* 
=============================================================================== 
```

And chaosresult

```
Name:         engine-nginx-pod-delete
Namespace:    litmus
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"litmuschaos.io/v1alpha1","kind":"ChaosResult","metadata":{"annotations":{},"name":"engine-nginx-pod-delete","namespace":"li...
API Version:  litmuschaos.io/v1alpha1
Kind:         ChaosResult
Metadata:
  Creation Timestamp:  2019-10-10T14:31:38Z
  Generation:          2
  Resource Version:    223401
  Self Link:           /apis/litmuschaos.io/v1alpha1/namespaces/litmus/chaosresults/engine-nginx-pod-delete
  UID:                 ab0acae0-eb6a-11e9-9684-025000000001
Spec:
  Experimentstatus:
    Phase:    <nil>
    Verdict:  pass
Events:       <none>

```

The experiment i ran

```
Name:         pod-delete
Namespace:    litmus
Labels:       <none>
Annotations:  <none>
API Version:  litmuschaos.io/v1alpha1
Description:
  Message:  Deletes a pod belonging to a deployment/statefulset/daemonset

Kind:  ChaosExperiment
Metadata:
  Creation Timestamp:  2019-10-10T14:30:24Z
  Generation:          1
  Resource Version:    223149
  Self Link:           /apis/litmuschaos.io/v1alpha1/namespaces/litmus/chaosexperiments/pod-delete
  UID:                 7f15c04d-eb6a-11e9-9684-025000000001
Spec:
  Definition:
    Args:
      -c
      ansible-playbook ./experiments/generic/pod_delete/pod_delete_ansible_logic.yml -i /etc/ansible/hosts -vv; exit 0
    Command:
      /bin/bash
    Env:
      Name:   ANSIBLE_STDOUT_CALLBACK
      Value:  default
      Name:   TOTAL_CHAOS_DURATION
      Value:  15
      Name:   CHAOS_INTERVAL
      Value:  5
      Name:   LIB
      Value:  
    Image:    kmjayadeep/ansible-runner:latest
    Labels:
      Name:  pod-delete
Events:      <none>

```

and the docker image I used for testing

```
REPOSITORY                                            TAG                            IMAGE ID            CREATED             SIZE
kmjayadeep/ansible-runner                             latest                         bc926e06b879        10 hours ago        298MB
```

**Comment by kmjayadeep** [comment]
@ksatchit @chandankumar4 Could you please take a look?

**Pull request merged**
