### PR TITLE
Aligning the tables for Adopters.md

### PR DESCRIPTION
**Pull request by ajeshbaby**
Changes
- Adding wescale chaos engineering reference link 
- Add alignment for borders.

### CODE REVIEW

**Comment by ajeshbaby** [comment]
@akria18 Can you review the link if it's fine to add in the adopter's list.  We can go ahead and merge the same.

**Review by ksatchit — APPROVED** [review]
LGTM

**Review by akria18 — CHANGES_REQUESTED** [review]

**Comment by ajeshbaby** [comment]
Addressed the comment.

**Review by akria18 — COMMENTED** [review]
LGTM

**Review by akria18 — APPROVED** [review]

**Review by ksatchit — APPROVED** [review]

**Pull request merged**
