### PR TITLE
chore(litmus-portal): Add unified modal component

### PR DESCRIPTION
**Pull request by saswatamcode**
## Proposed changes
Making a unified modal component, `Unimodal`. This unified modal does not need to be styled again when it needs to be used. Only content passed inside the modal needs to be styled. Can pass flags such as `hasCloseBtn` to automatically add a close button to the top right, `isDark` to make modal background dark and `textAlign` to set alignment. Most modals have been adapted to use the unified modal. Pertaining to issue #1887 
## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Special notes for your reviewer:
This does not bring about a difference in the modal responsiveness behaviour as such. That needs to be handled separately.

### CODE REVIEW

**Review by ishangupta-ds — APPROVED** [review]
@rajdas98 PTAL.

**Review by arkajyotiMukherjee — CHANGES_REQUESTED** [review]
This is a nice PR...just one minor change:
The Modal will be in the layouts folder.

**Comment by ishangupta-ds** [comment]
@arkajyotiMukherjee PTAL.

**Review by ishangupta-ds — APPROVED** [review]

**Comment by arkajyotiMukherjee** [comment]
Have the changes from @S-ayanide made @saswatamcode ?

**Comment by saswatamcode** [comment]
No, I'll be making them within a day or two.

**Review by S-ayanide — APPROVED** [review]

**Review by arkajyotiMukherjee — APPROVED** [review]

**Review by amityt — APPROVED** [review]
LGTM

**Comment by ishangupta-ds** [comment]
@rajdas98 PTAL.

**Pull request merged**
