### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rajdeepbhattacharya**
Added way to access minikube service url. Also added env variable LITMUS_PORTAL_NAMESPACE to NODE_NAME/EXTERNAL_IP/NODE_PORT variable.

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Review by ishangupta-ds — CHANGES_REQUESTED** [review]
This env. variable is not used for cluster scoped installation @rajdeepbhattacharya in this case the command will fail to execute as intended, you may create separate steps for obtaining url for the namespaced install and cluster scoped install ( by default cluster manifest installs litmus in the litmus namespace ) cc: @rajdas98 @ajeshbaby

**Comment by rajdeepbhattacharya** [comment]
> This env. variable is not used for cluster scoped installation @rajdeepbhattacharya in this case the command will fail to execute as intended, you may create separate steps for obtaining url for the namespaced install and cluster scoped install ( by default cluster manifest installs litmus in the litmus namespace ) cc: @rajdas98 @ajeshbaby

@ishangupta-ds actually in the docs env variable `LITMUS_PORTAL_NAMESPACE` is already taken as an input, then the whole setup should continue with the same namespace, not necessarily litmus namespace. I could see that in the yaml files also litmus namespace is used. The basis of my change request was only based on the user input and if you want to make the namespace dynamic based on user input. Also the node ip command doesn't work in minikube that's why I have shared the minikube command to get the endpoint ip.

**Review by rajdas98 — APPROVED** [review]
Looks good to me. 
@ishangupta-ds - It's just an env, I don't think it will break anything. Soon we will move to the helm as the main installation procedure.

**Comment by rajdas98** [comment]
@rajdeepbhattacharya Can you update your PR branch?

**Comment by ishangupta-ds** [comment]
@rajdas98 we may have to use a similar template for cluster scope installation where user has a choice to install portal in any namespace instead of the hardcoded litmus ns. We may need to add this change like @rajdeepbhattacharya suggests is on the docs, may be via helm we are giving the configuration option, the readme and cluster manifest are still having litmus as namespace.

**Review by ishangupta-ds — APPROVED** [review]

**Pull request merged**
