### PR TITLE
Added Kublr space/cluster selector in the monitoring dashboards

### PR DESCRIPTION
**Pull request by olegch**
## Proposed changes

Added Kublr space and cluster selector in Kublr-specific grafana dashboards to show multi-cluster capabilities.
Minor fixes in README for Kublr monitoring integration

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

The fixes are in docs and grafana dashboard specific for Kublr integration only, no Litmus files are affected

### CODE REVIEW

**Comment by whitetiger1399** [comment]
can you sign the commits as the DCO check is not complete

**Comment by whitetiger1399** [comment]
```
❯ kubectl annotate svc -n litmus --overwrite \
  chaos-monitor chaos-operator-metrics litmus-eventrouter \
  'prometheus.io/scrape=true'

service/chaos-monitor annotated
service/chaos-operator-metrics annotated
service/litmus-eventrouter annotated
❯ kubectl annotate svc -n litmus --overwrite \
kubectl annotate svc -n litmus \
  chaos-monitor chaos-operator-metrics litmus-eventrouter \
  'prometheus.io/scrape=true'
service/chaos-monitor annotated
service/chaos-operator-metrics annotated
service/litmus-eventrouter annotated
Error from server (NotFound): services "kubectl" not found
Error from server (NotFound): services "annotate" not found
Error from server (NotFound): services "svc" not found
```
 in the readme writing the kubectl command after --overwrite tag is giving an error the working version is also tested and given above

**Review by whitetiger1399 — APPROVED** [review]
LGTM

**Review by ishangupta-ds — APPROVED** [review]

**Pull request merged**
