### PR TITLE
Feat: Added feature to display previos values of users fullname and e…

### PR DESCRIPTION
**Pull request by duttaANI**
…mail set in accounts tab

To discuss-
1) box at top right doesnt load new email when changed immediately

2) both values must be set and then save button gets activated

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue:

[issue: ](https://github.com/litmuschaos/litmus/issues/3158)

Changes are made to display full name and user email 

To handle empty string , the handleNameChange and handleEmailChange will strip "space" automatically while user updates values

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

To enable save button both values i.e. full name and email must be set . Previously it was limited to full name only

### CODE REVIEW

**Review by Saranya-jena — CHANGES_REQUESTED** [review]
Can you remove all the unused comments?

**Comment by Saranya-jena** [comment]
Is your approach partially solving the issue as per your comment: https://github.com/litmuschaos/litmus/issues/3158#issuecomment-922364793 ?

**Comment by duttaANI** [comment]
I have solved the issue of displaying old full name and old email values set by the user .

After this I encountered a problem that user was not able to backspace the first letter which I had mentioned [here](https://github.com/litmuschaos/litmus/issues/3158#issuecomment-922364793).
However I solved this problem by replacing empty string by a "space" and  trimming the "space" from beginning of the string (since a condition is there for name to be valid it should not begin with a space) .

Now user would be able to edit both values without any issue.

Two extra points I would like to share with the developers  -

- First one is related to save button being activated.

code before this PR

```
<ButtonFilled
              disabled={
                !(
                  personaData.fullName.length &&
                  !loading
                )
              }
              onClick={handleSubmit}
            >
```

The issue with above code is that if the user chooses to only edit his email the save button still remains disabled .

To fix this I changed it to following -

```
<ButtonFilled
              disabled={
                !(
                  personaData.email.length &&
                  personaData.fullName.length &&
                  !loading
                )
              }
              onClick={handleSubmit}
            >
```

The catch here is that the user would have to click on both input fields to get the save button activated.

- Second - It seems that there is an issue with top right box , it doesn't update email value after user changes it . However if the user logs in again it would update


litmus

**Comment by Saranya-jena** [comment]
I think the email is being extracted from JWT token `getUserEmail()` . In that case, it will only get updated when a new token is generated(after login). So instead of taking it from token , can you try using this query: `GET_USER_INFO`(Graphql endpoint) or `/getUser/:uid` (Rest endpoint) to fetch the user details and set the updated email?

**Comment by duttaANI** [comment]
> Is your approach partially solving the issue as per your comment: [#3158 (comment)](https://github.com/litmuschaos/litmus/issues/3158#issuecomment-922364793) ?
> 
> The following approach should solve this issue completely:
> 
> ```
> const name: string = dataA?.getUser.name ?? ''; // TODO: Check if can be replaced with JWT based data.
>  const email: string = dataA?.getUser.email ?? '';
> ```
> 
> You can remove this section completely and assign empty strings as default values in `personaData `. Then add `onCompleted` in `getUser ` query where you'll be updating the `personaData` state with the latest data you got.
> 
> Also do add a `fetchPolicy` in the query and set it to `cache-and-network` . Can you try this approach?

Yes this approach solves the issue completely.

**Review by Saranya-jena — APPROVED** [review]

**Review by SarthakJain26 — APPROVED** [review]

**Comment by Saranya-jena** [comment]
Thank you for the PR 🎉

**Comment by duttaANI** [comment]
Thanks for guiding me towards correct approach.

**Pull request merged**
