### PR TITLE
Added support for Reporting 

### PR DESCRIPTION
**Pull request by sumitnagal**
**What this PR does / why we need it**:
Report flag to get insight of chaos execution, control via ENV flag

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Enhancement to support the Report formatting so that Later we can add to K8 event

**Checklist**

* [ ] Does this PR have a corresponding GitHub issue?
* [ ] Have you included relevant README for the chaoslib/experiment with details?
* [ ] Have you added debug messages where necessary? 
* [ ] Have you added task comments where necessary? 
* [ ] Have you tested the changes for possible failure conditions?
* [ ] Have you provided the positive & negative test logs for the litmusbook execution?
* [ ] Does the litmusbook ensure idempotency of cluster state?, i.e., is cluster restored to original state?
* [ ] Have you used non-shell/command modules for Kubernetes tasks?
* [ ] Have you (jinja) templatized custom scripts that is run by the litmusbook, if any? 
* [ ] Have you (jinja) templatized Kubernetes deployment manifests used by the litmusbook, if any?
* [ ] Have you reused/created util functions instead of repeating tasks in the litmusbook?
* [ ] Do the artifacts follow the appropriate directory structure? 
* [ ] Have you isolated storage (eg: OpenEBS) specific implementations, checks? 
* [ ] Have you isolated platform (eg: baremetal kubeadm/openshift/aws/gcloud) specific implementations, checks?  
* [ ] Are the ansible facts well defined? Is the scope explicitly set for playbook & included utils?
* [ ] Have you ensured minimum/careful usage of shell utilities (awk, grep, sed, cut, xargs etc.,)?
* [ ] Can the limtusbook be executed both from within & outside a container (configurable paths, no hardcode)?
* [ ] Can you suggest the minimal resource requirements for the litmusbook execution?
* [ ] Does the litmusbook job artifact carry comments/default options/range for the ENV tunables?
* [ ] Has the litmusbooks been linted? 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sumitnagal** [comment]
Work in Progress ..don't Merge

**Comment by Jasstkn** [comment]
@sumitnagal any news about that? I'm very interested in that feature.

**Comment by ksatchit** [comment]
Hi @Jasstkn - I suppose @sumitnagal has already added this. We are yet to document the usage. I suppose this should be available soon. 

https://github.com/litmuschaos/chaos-charts/blob/master/charts/chaostoolkit/experiments.yaml#L63

The experiment logic for python/chaostoolkit will be placed here going forward (over this repo): https://github.com/litmuschaos/litmus-python/tree/master/chaostoolkit/chaostest/kubernetes

Stay tuned, we will get back soon!

**Comment by Jasstkn** [comment]
> Hi @Jasstkn - I suppose @sumitnagal has already added this. We are yet to document the usage. I suppose this should be available soon.
> 
> https://github.com/litmuschaos/chaos-charts/blob/master/charts/chaostoolkit/experiments.yaml#L63
> 
> The experiment logic for python/chaostoolkit will be placed here going forward (over this repo): https://github.com/litmuschaos/litmus-python/tree/master/chaostoolkit/chaostest/kubernetes
> 
> Stay tuned, we will get back soon!

I'm looking forward description of those changes. Also, is there any way to run tests which has been written for chaostoolkit? Maybe there is some converter?

**Comment by ksatchit** [comment]
Here are the sequence of steps you could follow: 

- Install chaos operator

`kubectl apply -f https://litmuschaos.github.io/pages/litmus-operator-v1.3.0.yaml`

- Install chaostoolkit experiment CR

`kubectl apply -f https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/chaostoolkit/k8-pod-delete/experiment.yaml` -n litmus

- Setup rbac for experiment execution

  **Notes**: 
  - Please update the service account spec and clusterRoleBinding spec to reflect namespace `litmus` instead of namespace `msaasfmea4-perf-infra-usw2-ppd-pfi`

`kubectl apply -f https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/chaostoolkit/k8-pod-delete/rbac-admin.yaml`

- Prepare the chaosengine CR

   **Notes**: 
   - Update the chaosengine name to a suitable one depending on your usecase 
   - Please update the chaosengine resource namespace to litmus. Also, provide the namespace of the target app you would like to kill (`appinfo.appns`), and,
   - Unique label of your application (`appinfo.applabel`) in the form key=value
   - Provide the kubernetes `kind` of the target application(`appinfo.appkind`) : deployment, statefulset,daemonset
   - If you would like to further filter the apps for selection, [annotate](https://docs.litmuschaos.io/docs/getstarted/#annotate-your-application) your app's metadata with `litmuschaos.io/chaos="true"`. If not, keep the `.spec.annotationCheck` in the chaosengine to "false". 
   - Update the "NAME_SPACE", "LABEL_NAME" ENVs on the chaosengine to reflect info provided in spec.appinfo. The LABEL_NAME seems to hold only the value. Is the label key always expected to be  `app` @sumitnagal ? 
 
  
`kubectl apply -f https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/chaostoolkit/k8-pod-delete/engine.yaml`

These above steps will cause the following results: 

- A pod named  `<chaosengine-name>-runner` is launched in the litmus namespace (manages exp)
- Followed by creation of another pod `<k8-pod-delete-<hash>>`  (runs exp)

Watch for the pods in your app ns - to see it getting terminated. 

cc: @sumitnagal please review for accuracy. 

Some of the above steps will be automated, made less redundant in future.

**Comment by ksatchit** [comment]
This capability is added and described in [litmus-python](https://github.com/litmuschaos/litmus-python)

**Pull request closed without merging**
