### PR TITLE
adding service accounts and securityContexts

### PR DESCRIPTION
**Pull request by mtcolman**
## Proposed changes

Adding Service Accounts and securityContexts to improve compatibility with OpenShift (due to SCCs)

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

This is linked to issue #3882

### CODE REVIEW

**Comment by tomkivlin** [comment]
Have confirmed this works (and is needed) for litmus-3.0.0-beta8 on OCP.

**Comment by namkyu1999** [comment]
Hi @mtcolman 
ServiceAccount is already implemented in the latest version.

https://github.com/litmuschaos/litmus/blob/ac62acfe1920cbf037d8782655b26f8c9fbb9c16/mkdocs/docs/3.0.0-beta12/litmus-3.0.0-beta12.yaml#L421-L425

**Comment by mtcolman** [comment]
@namkyu1999 my proposed additions/code change is different to that. The workloads need additional serviceAccounts, and that's what I've added:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmus-server-account
  namespace: litmus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmus-auth-server-account
  namespace: litmus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmus-frontend-account
  namespace: litmus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmus-mongo-account
  namespace: litmus
---
```

See the additional service accounts alongside the existing `litmus-server-account` serviceAccount.

These are then used by deployments in the same yaml - and this aligns with #3882. E.g.:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litmusportal-frontend
  namespace: litmus
  ...
spec:
  ...
  template:
    ...
    spec:
      ...
      serviceAccountName: litmus-frontend-account
```

**Comment by namkyu1999** [comment]
Hi @mtcolman 
How about adding your changes to [3.0.0-beta12](https://github.com/litmuschaos/litmus/tree/master/mkdocs/docs/3.0.0-beta12) instead of 3.0.0-beta4? If you want to make changes to Litmus version 2, add your changes to [2.14.0](https://github.com/litmuschaos/litmus/tree/master/mkdocs/docs/2.14.0)

**Comment by Saranya-jena** [comment]
Closing this as it has been added as part of Litmus 3.0

**Pull request closed without merging**
