### PR TITLE
type(docs): Update GraphQL document (support 3.11.0)

### PR DESCRIPTION
**Pull request by suyeon-jung-dev**
## Proposed changes

This PR adds:
- Replacing the GraphQL docs dociql with spectaql
    - It was created using [spectaQL](https://github.com/anvilco/spectaql) tool, customized similarly to a previous version of the GraphQL documents.
- Updating GraphQL docs v3.9.x and higher (3.9.x, 3.10.x, 3.11.x)
- Adding common error response information
- Update the latest version of GraphQL docs URL (v3.11.x) on Litmus Documentation Page (/litmus/experiments/api/contents)

 

Solved #4771 

GraphQL API docs demo v3.9.0: https://suyeon-jung-dev.github.io/litmus/graphql/v3.9.0/api.html
GraphQL API docs demo v3.10.0: https://suyeon-jung-dev.github.io/litmus/graphql/v3.10.0/api.html
GraphQL API docs demo v3.11.0: https://suyeon-jung-dev.github.io/litmus/graphql/v3.11.0/api.html

image

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Comment by suyeon-jung-dev** [comment]
Actually there is a thing I forgot to tell you guys.

To create with the spactaQL tool, we need to change one of Query/Mutation/Subscriptions to parent type.
You can see [this commit](https://github.com/litmuschaos/litmus/pull/4791/commits/3b4af9876693df42ba5f8177b6111cf48aecf98b).
I think `graphql/validation/validate.js` couldn't generate with no-parent Query/Mutation/Subscription SDL files.

Do you guys think this method seems fine?

**Comment by neelanjan00** [comment]
@suyeon-jung-dev Here are a couple of things we should add:
- A window to try the API for a given server URL (similar to Swagger).
- Provide examples of success and failure cases while documenting them.

**Comment by suyeon-jung-dev** [comment]
Hi, @neelanjan00 . If we need to add these two things, I'll look for other tools. Because SpectaQL doesn't support them.

- `A window to try the API for a given server URL (similar to Swagger).`
SpectaQL supports only api end point paths like below.
Screenshot 2024-08-19 at 6 30 52 PM

- `Provide examples of success and failure cases while documenting them `
SpectaQL supports only success case.
Screenshot 2024-08-19 at 6 43 42 PM

Thank you for your feedback :)

**Comment by suyeon-jung-dev** [comment]
> @suyeon-jung-dev Here are a couple of things we should add:
> 
> * A window to try the API for a given server URL (similar to Swagger).
> * Provide examples of success and failure cases while documenting them.
> 
> LMK if this sounds good?

Hi @neelanjan00 

I looked into the two things you asked about earlier, but I couldn't find any tools that have all the features we need. 🥲

The tool we previously used, [dociql](https://github.com/wayfair/dociql), is no longer being updated — its last update was two years ago. Additionally, dociql can only be installed in a Python 2 environment. Even if we were to continue using it, we would still need to create a config.yaml file manually, which requires typing out every line.

Regarding the feature "A window to try the API for a given server URL (similar to Swagger)," I have some concerns about potential security issues. We can also use GraphQL Playground for this purpose instead.

Considering all of this, I think [SpectaQL](https://github.com/anvilco/spectaql) is the best option.

**Comment by neelanjan00** [comment]
> > @suyeon-jung-dev Here are a couple of things we should add:
> > 
> > * A window to try the API for a given server URL (similar to Swagger).
> > * Provide examples of success and failure cases while documenting them.
> > 
> > LMK if this sounds good?
> 
> Hi @neelanjan00
> 
> I looked into the two things you asked about earlier, but I couldn't find any tools that have all the features we need. 🥲
> 
> The tool we previously used, [dociql](https://github.com/wayfair/dociql), is no longer being updated — its last update was 2 years ago. Additionally, dociql can only be installed in a Python 2 environment. Even if we were to continue using it, we would still need to create a config.yaml file manually, which requires typing out every line.
> 
> Regarding the feature "A window to try the API for a given server URL (similar to Swagger)," I have some concerns about potential security issues. We can also use GraphQL Playground for this purpose instead.
> 
> Considering all of this, I think [SpectaQL](https://github.com/anvilco/spectaql) is the best option.

Okay sure, I guess we can just document the various success and failure cases for each API. We can skip the Swagger-like interface in favour of the in-built GraphQL playground.

**Comment by namkyu1999** [comment]
> Okay sure, I guess we can just document the various success and failure cases for each API. We can skip the Swagger-like interface in favour of the in-built GraphQL playground.

Hi @neelanjan00 ,

1. All open source that auto-generates GraphQL docs (DociQL, MagiDoc, SpectaQL...) make docs based on 'schema'.

In the case of an error, it depends on implementing the resolver function (not schema), so we have to check it manually to add it to the API docs for the error case. (It's time time-consuming job and hard to maintain)

2. Unlike REST API, GraphQL returns 200 OKs even in case of an error

All GraphQL queries and mutations return errors in a structure like List<Error>. In our codebase, we only return a single error. It also differs only in the message part of the error and does not return any other metadata or data.
- error Schema example (https://graphql.org/learn/validation/)
- multiple errors (https://gqlgen.com/reference/errors/#multiple-errors)

---

IMO, it would be much more efficient to add a page for common errors. This is because most errors coming from GraphQL servers are similar(authentication failure, MongoDB CRUD failure, etc.). SpectaQL supports adding pages using Markdown. So how about using this feature?

**Comment by neelanjan00** [comment]
> > Okay sure, I guess we can just document the various success and failure cases for each API. We can skip the Swagger-like interface in favour of the in-built GraphQL playground.
> 
> Hi @neelanjan00 , I tried to find many alternatives, but it seems unnecessary to create an error/success cases for every single request. (we already have success cases)
> 
> 1. All open source that auto-generates GraphQL docs (DociQL, MagiDoc, SpectaQL...) make docs based on 'schema'.
> 
> In the case of an error, it depends on implementing the resolver function (not schema), so we have to check it manually to add it to the API docs for the error case. (It's time time-consuming job and hard to maintain)
> 
> 2. Unlike REST API, GraphQL returns 200 OKs even in case of an error
> 
> All GraphQL queries and mutations return errors in a structure like List. In our codebase, we only return a single error. It also differs only in the message part of the error and does not return any other metadata or data.
> 
> * error Schema example (https://graphql.org/learn/validation/)
> * multiple errors (https://gqlgen.com/reference/errors/#multiple-errors)
> 
> IMO, it would be much more efficient to add a page for common errors. This is because most errors coming from GraphQL servers are similar(authentication failure, MongoDB CRUD failure, etc.). SpectaQL supports adding pages using Markdown. So how about using this feature?

Sounds good, this is what I meant as well actually, sorry for the confusion if any. Yes, having some sort of documentation around the success and most common failure messages for at least the most common mutations and queries will be a good way forward.

**Comment by suyeon-jung-dev** [comment]
I deployed a demo with branch `[feature/update-api-docs-3.9.1-deploy-test](https://github.com/suyeon-jung-dev/litmus/commits/feature/update-api-docs-3.9.1-deploy-test/)`.

You can check [3.9.x](https://suyeon-jung-dev.github.io/litmus/graphql/v3.9.x/api.html), [3.10.x](https://suyeon-jung-dev.github.io/litmus/graphql/v3.10.x/api.html), [3.11.x](https://suyeon-jung-dev.github.io/litmus/graphql/v3.11.x/api.html) version of GraphQL docs demo with those links.

**Review by namkyu1999 — APPROVED** [review]
LGTM 🚀

**Review by Saranya-jena — APPROVED** [review]

**Review by neelanjan00 — APPROVED** [review]

**Pull request merged**
