### PR TITLE
type(api-docs): Added analytics gql apis and authentication rest api docs

### PR DESCRIPTION
**Pull request by amityt**
## Proposed changes

This PR adds:
- Authentication REST API docs
- Analytics API docs
- Removed dupllicate docs directory from frontend

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Review by rajdas98 — CHANGES_REQUESTED** [review]
Please add a reference to `auth-server` api doc in graphql api docs.

**Comment by amityt** [comment]
> Please add a reference to `auth-server` api doc in graphql api docs.

@rajdas98 The auth apis can be accessed from the sidebar. Under the operation section, Authentication option is available.
https://amityt.github.io/litmus/api.html

**Comment by rajdas98** [comment]
> > Please add a reference to `auth-server` api doc in graphql api docs.
> 
> @rajdas98 The auth apis can be accessed from the sidebar. Under the operation section, Authentication option is available.
> https://amityt.github.io/litmus/api.html

Can you put it after the Introduction section? As authentication is the first step for any API call

**Comment by amityt** [comment]
Sure @rajdas98 Will make the change!

**Review by arkajyotiMukherjee — APPROVED** [review]

**Review by gdsoumya — APPROVED** [review]

**Pull request merged**
