### PR TITLE
Remove unused RBACs in GraphQL server

### PR DESCRIPTION
**Pull request by punithnayak**
Signed-off-by: punithnayak <punithnayak098@gmail.com>

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ x] I have signed the commit for DCO to be passed.
- [ x] Lint and unit tests pass locally with my changes
- [ x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ x] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Review by Saranya-jena — APPROVED** [review]
lgtm

**Review by amityt — APPROVED** [review]

**Comment by Saranya-jena** [comment]
@punithnayak Can you resolve the conflicts here, post that we will merge this.

**Comment by punithnayak** [comment]
> @punithnayak Can you resolve the conflicts here, post that we will merge this.

Sure sorry for the delay

**Review by SarthakJain26 — APPROVED** [review]

**Comment by Saranya-jena** [comment]
Can you resolve the conflicts, this PR has been pending for long time.

**Comment by RipulHandoo** [comment]
> Can you resolve the conflicts, this PR has been pending for long time.

I wasn't aware that a PR had already been raised for this issue. I've submitted a [new PR](https://github.com/litmuschaos/litmus/pull/4265). If @punithnayak is unable to resolve the conflicts, please consider reviewing my PR as an alternative solution.

**Comment by Saranya-jena** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
