### PR TITLE
refector: refectoring code to improve the readability and quality

### PR DESCRIPTION
**Pull request by yj-yoo**
## Proposed changes

- add cancel function return to avoid a context leak
- replace deprecated package
  - ioutil -> io
- simplify conditional expressions
- simplify if statements
- fix comments
- change variable from snake case to camel case
- add context.TODO()

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Review by namkyu1999 — APPROVED** [review]
LGTM 😎

**Review by SarthakJain26 — APPROVED** [review]

**Comment by Saranya-jena** [comment]
Hi @yj-yoo , can you please resolve the conflicts? And I see you have added changes in litmus-portal, litmus-portal will be archived soon, can you add those changes in chaoscenter if applicable?

**Comment by yj-yoo** [comment]
> Hi @yj-yoo , can you please resolve the conflicts? And I see you have added changes in litmus-portal, litmus-portal will be archived soon, can you add those changes in chaoscenter if applicable?

Even though it is a simple grammar correction, do I need to add it to "chaoscenter"? Where can I find out how to add more?

**Comment by Saranya-jena** [comment]
Actually we have removed litmus-portal as it was deprecated. Let me know how you would like to proceed. @yj-yoo

**Comment by yj-yoo** [comment]
@Saranya-jena When will 'litmus-portal' be deprecated? I think I'll be able to send the pr again next week. If it gets deprecated first, I'll work on it again.

**Comment by Saranya-jena** [comment]
> @Saranya-jena When will 'litmus-portal' be deprecated? I think I'll be able to send the pr again next week. If it gets deprecated first, I'll work on it again.

It's already deprecated and removed from the repo @yj-yoo . Feel free to send a PR on chaoscenter changes :))

**Pull request closed without merging**
