### PR TITLE
bump the Go image to 1.20

### PR DESCRIPTION
**Pull request by unclejack**
## Proposed changes
This PR bumps Go to 1.20. Go version 1.16 is old, unsupported and has known CVEs. These known vulnerabilities have been addressed in newer versions of Go.

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [X] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [X] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
n/a

### CODE REVIEW

**Comment by namkyu1999** [comment]
Thanks for the raise PR. But the Upgrade version of Go has lots of side effects. And I know that the Litmus team has a long-term plan for this topic. So how about resolving other issues first?

**Comment by unclejack** [comment]
@namkyu1999: Perhaps you could provide an example of such an incompatibility between this code base and a newer version of Go? It's a very bad idea to use old and unsupported versions of Go. Bugs which have long been fixed in the compiler are still present in Go 1.16. This isn't related to generating slower code. This is related to having correct Go code compiled to the wrong machine instructions.

I've sent this PR while evaluating litmus for a deployment. I understand if compiler bugs and security don't represent a concern for this project.

**Comment by namkyu1999** [comment]
hey @unclejack,
I fully understand that upgrading version of Go is really important.
But If you want to migrate successfully, you need to change more files than you do now.
For example, you also need to change files like go.mod, each backend component(graphql-server, authentication server …), and relevant libraries.

Here’s a sample comment: https://github.com/litmuschaos/litmus/pull/3923#discussion_r1160668942

Also, You need to make sure that the changes you make don't affect the current service.

The topic of raising the language version came up at the Litmus contributor meetup yesterday. If you'd like to address this issue, you can join the next meetup and share your thoughts, or you can join the litmus channel on Slack and say you're available for this issue. Since you haven't contributed to litmus yet, I'd recommend doing a little PR first.

**Comment by unclejack** [comment]
@namkyu1999: It's not that important that I haven't contributed to your project before. I'm familiar with Go.

Your initial reply left me with the impression that you speak in the name of all the maintainers and that such a change is undesirable. Based on what you've written in your second reply, it seems that it's perceived more as a technical issue.

I'll check what steps need to be taken to test the various components. If it's reasonable, I'll go through that process. Updating go.mod isn't an issue as far as I'm concerned. It's just a task.

In the end, it's not something I insist on doing at all costs.

**Pull request closed without merging**
