### PR TITLE
[WIP]Changed code architecture in Environment handler to use interface

### PR DESCRIPTION
**Pull request by punithnayak**
Signed-off-by: Punith nayak <npunith125@email.com>

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
#4121

### CODE REVIEW

**Comment by SohamRatnaparkhi** [comment]
Please check the DCO. You haven't signed your commits.

**Comment by punithnayak** [comment]
Hey @saranya-jena 
Could you kindly confirm if this is what you wanted? If necessary, please provide any specific details or modifications to make it

**Comment by Saranya-jena** [comment]
Did you run the graphql server? I see there are no changes in files calling these functions.

**Comment by SohamRatnaparkhi** [comment]
@punithnayak, you will need to make necessary changes wherever these functions are being called. Previously, the functions weren't being implemented by any interface, and hence they could be directly called by importing the package (packageName.function()).
However, with the recent changes you have made in this PR, a struct of type EnvironmentHandler, which will be returned by the NewEnvHandler method you have added, needs to be created in the file where these functions are intended to be called using it. (my_struct_variable_name.function()).

You can probably checkout service.go in chaos-experiments or chaos-experiment-runs package as it has a similar interface-struct implementation.

**Comment by Saranya-jena** [comment]
Closing this PR due to inactivity

**Pull request closed without merging**
