### PR TITLE
YAML to JSON conversion and a small fix added.

### PR DESCRIPTION
**Pull request by Jonsy13**
Signed-off-by: Vedant Shrotria <vedant.shrotria@mayadata.io>

## Proposed changes

**This PR will** 

- **Add the Json conversion and Escaping of yaml**
- **Small fix: Now user won't be allowed to continue without selecting a workflow.**

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [X] New feature (non-breaking change which adds functionality)
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [X] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [X] I have signed the commit for DCO to be passed.
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Comment by rajdas98** [comment]
@Jonsy13 I test this PR. In mongoDB we are getting this string- 
```
"workflow_manifest" : "\"{\\n  \\\"apiVersion\\\": \\\"argoproj.io/v1alpha1\\\",\\n  \\\"kind\\\": \\\"CronWorkflow\\\",\\n  \\\"metadata\\\": {\\n    \\\"name\\\": \\\"node-cpu-cron-wf\\\"\\n  },\\n  \\\"spec\\\": {\\n    \\\"schedule\\\": \\\"5/10 * * * *\\\",\\n    \\\"concurrencyPolicy\\\": \\\"Forbid\\\",\\n    \\\"startingDeadlineSeconds\\\": 0,\\n    \\\"workflowSpec\\\": {\\n      \\\"entrypoint\\\": \\\"argowf-chaos\\\",\\n      \\\"serviceAccountName\\\": \\\"argo-chaos\\\",\\n      \\\"templates\\\": [\\n        {\\n          \\\"name\\\": \\\"argowf-chaos\\\",\\n          \\\"steps\\\": [\\n            [\\n              {\\n                \\\"name\\\": \\\"run-node-cpu-hog\\\",\\n                \\\"template\\\": \\\"run-node-cpu-hog\\\"\\n              }\\n            ]\\n          ]\\n        },\\n        {\\n          \\\"name\\\": \\\"run-node-cpu-hog\\\",\\n          \\\"inputs\\\": {\\n            \\\"artifacts\\\": [\\n              {\\n                \\\"name\\\": \\\"run-node-cpu-hog\\\",\\n                \\\"path\\\": \\\"/tmp/chaosengine-1.yaml\\\",\\n                \\\"raw\\\": {\\n                  \\\"data\\\": \\\"apiVersion: litmuschaos.io/v1alpha1\\\\nkind: ChaosEngine\\\\nmetadata:\\\\n  name: node-cpu-hog\\\\n  namespace: litmus\\\\nspec:\\\\n  appinfo:\\\\n    appns: kube-system\\\\n    applabel: \\\\\\\"k8s-app=kube-proxy\\\\\\\"\\\\n    appkind: daemonset\\\\n  jobCleanUpPolicy: retain\\\\n  monitoring: true\\\\n  annotationCheck: 'false'\\\\n  engineState: 'active'\\\\n  chaosServiceAccount: litmus-admin\\\\n  experiments:\\\\n    - name: node-cpu-hog\\\\n      spec:\\\\n        components:\\\\n          env:\\\\n            - name: TOTAL_CHAOS_DURATION\\\\n              value: \\\\\\\"60\\\\\\\"\\\\n            - name: NODE_CPU_CORE\\\\n              value: \\\\\\\"\\\\\\\"\\\\n\\\"\\n                }\\n              }\\n            ]\\n          },\\n          \\\"container\\\": {\\n            \\\"image\\\": \\\"lachlanevenson/k8s-kubectl\\\",\\n            \\\"command\\\": [\\n              \\\"sh\\\",\\n              \\\"-c\\\"\\n            ],\\n            \\\"args\\\": [\\n              \\\"kubectl apply -f /tmp/chaosengine-1.yaml -n litmus\\\"\\n            ]\\n          }\\n        }\\n      ]\\n    }\\n  }\\n}\""
```

Which is stringified of Stringified JSON. It should be single stringified JSON

**Comment by rajdas98** [comment]
Use this tool to test escape and unescape of string
https://www.freeformatter.com/json-escape.html

**Comment by Jonsy13** [comment]
Output from Mongodb -- 
`"workflow_manifest" : "{\n  \"apiVersion\": \"argoproj.io/v1alpha1\",\n  \"kind\": \"CronWorkflow\",\n  \"metadata\": {\n    \"name\": \"node-cpu-cron-wf\"\n  },\n  \"spec\": {\n    \"schedule\": \"5/10 * * * *\",\n    \"concurrencyPolicy\": \"Forbid\",\n    \"startingDeadlineSeconds\": 0,\n    \"workflowSpec\": {\n      \"entrypoint\": \"argowf-chaos\",\n      \"serviceAccountName\": \"argo-chaos\",\n      \"templates\": [\n        {\n          \"name\": \"argowf-chaos\",\n          \"steps\": [\n            [\n              {\n                \"name\": \"run-node-cpu-hog\",\n                \"template\": \"run-node-cpu-hog\"\n              }\n            ]\n          ]\n        },\n        {\n          \"name\": \"run-node-cpu-hog\",\n          \"inputs\": {\n            \"artifacts\": [\n              {\n                \"name\": \"run-node-cpu-hog\",\n                \"path\": \"/tmp/chaosengine-1.yaml\",\n                \"raw\": {\n                  \"data\": \"apiVersion: litmuschaos.io/v1alpha1\\nkind: ChaosEngine\\nmetadata:\\n  name: node-cpu-hog\\n  namespace: litmus\\nspec:\\n  appinfo:\\n    appns: kube-system\\n    applabel: \\\"k8s-app=kube-proxy\\\"\\n    appkind: daemonset\\n  jobCleanUpPolicy: retain\\n  monitoring: true\\n  annotationCheck: 'false'\\n  engineState: 'active'\\n  chaosServiceAccount: litmus-admin\\n  experiments:\\n    - name: node-cpu-hog\\n      spec:\\n        components:\\n          env:\\n            - name: TOTAL_CHAOS_DURATION\\n              value: \\\"60\\\"\\n            - name: NODE_CPU_CORE\\n              value: \\\"\\\"\\n\"\n                }\n              }\n            ]\n          },\n          \"container\": {\n            \"image\": \"lachlanevenson/k8s-kubectl\",\n            \"command\": [\n              \"sh\",\n              \"-c\"\n            ],\n            \"args\": [\n              \"kubectl apply -f /tmp/chaosengine-1.yaml -n litmus\"\n            ]\n          }\n        }\n      ]\n    }\n  }\n}"`

**Review by oumkale — APPROVED** [review]

**Comment by rajdas98** [comment]
This PR is good. But I am not able to test this PR due to that
authentication issue. I will merge it after the test

**Comment by oumkale** [comment]
@Jonsy13 I have added a small fix for hasCloseBtn.

**Review by arkajyotiMukherjee — APPROVED** [review]

**Review by ishangupta-ds — APPROVED** [review]

**Review by rajdas98 — APPROVED** [review]

**Pull request merged**
