### PR TITLE
Add Chinese translation of the README.md

### PR DESCRIPTION
**Pull request by hanlins**
## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:
Chinese translation for the README document. @prithvi1307.

### CODE REVIEW

**Review by ajeshbaby — APPROVED** [review]
LGTM

**Review by S-ayanide — APPROVED** [review]

**Comment by S-ayanide** [comment]
Thanks, @hanlins for sending a PR 🎉 

Please wait for our maintainers to review this in order to get this merged as soon as possible. Thank you for your valuable contribution. 🥇

**Comment by prithvi1307** [comment]
@hanlins Can you please share your email id for us to reach out and send you swags?

**Comment by hanlins** [comment]
> @hanlins Can you please share your email id for us to reach out and send you swags?

Sure @prithvi1307, thanks for involving me! I've PMed my contact on k8s slack.

**Pull request merged**
