### PR TITLE
Fix path collisions on case-sensitive systems

### LINKED ISSUE #2178: path collision while cloning the repo
**What happened**:

While cloning the repo on a case-insensitive file system (Windows), I faced the following problem.

Capture

**What you expected to happen**:

It is not possible in that Edit.svg and edit.svg to exist at the same time - they are considered the same file in some systems, this would cause conflict for anyone that clones the repo.

**How to reproduce it (as minimally and precisely as possible)**:

run `git clone https://github.com/litmuschaos/litmus.git` on any case-insensitive system (OSX/Windows)

**Anything else we need to know?**:

the front-end only uses Edit.svg, so edit.svg is obsolete. I can make a quick PR that solves this conflict.

### PR DESCRIPTION
**Pull request by parshnt**
## Proposed changes

- [edit.svg](https://github.com/litmuschaos/litmus/blob/master/litmus-portal/frontend/public/icons/edit.svg) is obsolete and causes path collisions on case-sensitive systems like Windows, OSX. (see  #2178)

- I've removed `/litmus-portal/frontend/public/icons/edit.svg` 

fixes #2178

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Dependency
None

## Special notes for your reviewer:
None

### CODE REVIEW

**Comment by parshnt** [comment]
Hello @arkajyotiMukherjee @rajdas98 

Can you review my PR.
Thanks

**Review by arkajyotiMukherjee — DISMISSED** [review]

**Comment by arkajyotiMukherjee** [comment]
there's a conflict @parshnt can you remove that and add another commit
- pull from upsteam master branch
- resolve conflicts
- make a new commit
Note: you don't have to create a new PR
you can tag me in this PR if you face any problems

**Comment by parshnt** [comment]
Hello @arkajyotiMukherjee 

the conflict is resolved now :)

**Review by arkajyotiMukherjee — APPROVED** [review]

**Comment by arkajyotiMukherjee** [comment]
Thanks for sending the PR @parshnt 
Open-source contributions like yours, make this project alive and thriving

**Comment by parshnt** [comment]
@arkajyotiMukherjee can you assign it to someone else for review, I'm trying to get it merged before hactoberfest ends in two days.

**Review by amityt — APPROVED** [review]

**Review by Jonsy13 — APPROVED** [review]

**Pull request merged**
