### PR TITLE
Fix bug: Move the CUSTOM_TLS_CERT from subscriber config to subscribe…

### PR DESCRIPTION
**Pull request by RipulHandoo**
…r secret

## Proposed changes

It Move the CUSTOM_TLS_CERT from subscriber config to subscriber secret.
fixes [#3943](https://github.com/litmuschaos/litmus/issues/3943)

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Comment by RipulHandoo** [comment]
Hey @namkyu1999 , could you review this and help identify why the checks aren't passing?

**Comment by namkyu1999** [comment]
Hey @RipulHandoo , You don't have to care about `backend-unit-tests` check. It's not your problem

**Review by imrajdas — APPROVED** [review]

**Review by namkyu1999 — APPROVED** [review]

**Comment by Saranya-jena** [comment]
@RipulHandoo have you tested the changes?

**Review by Jonsy13 — APPROVED** [review]
Looks good, please make same changes under namespace directory as well.

**Comment by Saranya-jena** [comment]
closing due to inactivity

**Pull request closed without merging**
