### PR TITLE
Adding changes to frontend for interleaving chaos events on litmus-ui graphs.

### PR DESCRIPTION
**Pull request by ishangupta-ds**
## Proposed changes

* Changes for chaos event interleaving
* added `**/build/` to .gitignore

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Special notes for your reviewer:
PR for 2.0 Beta 1

### CODE REVIEW

**Comment by rajdas98** [comment]
I don't see any new imports. Can you reset package-lock.json

**Comment by ishangupta-ds** [comment]
> I don't see any new imports. Can you reset package-lock.json

if i reset then testing the changes wont be possible without running once, some packages have been updated with peer dependencies i suppose so it got updated just with an `npm install` @rajdas98

**Comment by ishangupta-ds** [comment]
> I don't see any new imports. Can you reset package-lock.json

@whitetiger1399 will be raising another PR to update `litmus-ui` so this will again change

**Review by whitetiger1399 — DISMISSED** [review]
LGTM

**Review by vanshBhatia-A4k9 — APPROVED** [review]

**Review by Saranya-jena — APPROVED** [review]

**Review by vanshBhatia-A4k9 — APPROVED** [review]
Can you please see if the changes BCH is suggesting are possible as well

**Review by whitetiger1399 — APPROVED** [review]
LGTM

**Review by amityt — APPROVED** [review]

**Comment by ishangupta-ds** [comment]
> Can you please see if the changes BCH is suggesting are possible as well

That file we will be removing in consecutive PRs for v2 it.. panel content would be updated then.

**Review by Saranya-jena — APPROVED** [review]

**Review by SarthakJain26 — APPROVED** [review]

**Pull request merged**
