### PR TITLE
(Draft): Fixing all Golang Lint issue and adding golangci-lint in the GitHub workflow

### LINKED ISSUE #2649: Add golang-ci lint check in build pipeline and remove backend and frontend checks from push pipeline

### PR DESCRIPTION
**Pull request by specter25**
## Proposed changes
 - Format exiting code according to golangci-lint
 - Add golang-ci lint in build pipeline
 - Remove frontend and backend checks from push pipeline
 - this fixes #2649 

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Comment by gdsoumya** [comment]
Too many code changes cannot be merged without proper testing. Can you just setup the golint for the goimport and gofmt checks. Other checks can be added later.
There should be some option for linters in theis github action similar to the original golanci-lint https://golangci-lint.run/usage/linters/

**Comment by specter25** [comment]
Sir go imports is already working as a separate CI check , can i add gofmt as a check without using golangci-lint ?

**Comment by rajdas98** [comment]
I think we need to fix all linting issue. Let's have this PR after the release (15April) with proper testing.

**Comment by specter25** [comment]
Yes @rajdas98  sir sure , I need to work on this a little more , the goling-ci lint is giving timeout errors in the pipeline , hopefully i will fix it by then

**Comment by specter25** [comment]
@rajdas98 sir , i have made all the lint fixes and intergarated go-lang ci-lint in  CI/CD as well .Sir all the lint tests are passing , put one test from better code hub is failing . Sir , how can i fix it ?

**Comment by rajdas98** [comment]
Closing this PR due to some large merge conflicts. Please raise a new PR for it.

**Pull request closed without merging**
