### PR TITLE
Hitting Enter advances Welcome Modal

### LINKED ISSUE #2133: Hitting Enter key does not work in the Welcome Modal.
**What happened**:
As visible in the below screenshot, upon entering the details in the welcome modal, hitting the enter key does not work and a user has to manually click on the "Continue" Button to submit the details and move to the next screen.

Screenshot from 2020-09-30 20-37-49

**What you expected to happen**:

Ideally, After the user has filled the information, they should be able to hit the enter key and move on to the next screen.

**How to reproduce it (as minimally and precisely as possible)**:

Launch the portal and login as a first time user or create a new user in the Setting/User Management/ section to access the welcome modal component.

### PR DESCRIPTION
**Pull request by rafaeelaudibert**
## Proposed changes

* Fix a typo where the translation for the `welcomeModal` had the `welcomeModel` key
* Added the ability to go from step to step in the welcomeModal through the enter key

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:
Closes #2133

### CODE REVIEW

**Review by S-ayanide — APPROVED** [review]

**Review by arkajyotiMukherjee — APPROVED** [review]
Thank you for the PR...this is a good change @rafaeelaudibert 
Great to see contributors such as yourself ❤️‍🔥

**Review by arkajyotiMukherjee — CHANGES_REQUESTED** [review]
hey @rafaeelaudibert can you update your PR with this change...our frontend CI build check failed
```

/home/circleci/project/litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
  279:65  error  Delete `,`  prettier/prettier
  314:65  error  Delete `,`  prettier/prettier
  375:65  error  Delete `,`  prettier/prettier
  407:65  error  Delete `,`  prettier/prettier

✖ 4 problems (4 errors, 0 warnings)
  4 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by rafaeelaudibert** [comment]
Hello @arkajyotiMukherjee! If I fix this error, the "Codacy/PR Quality Review" also fails, saying that I need the comma hahahah. Anyways, I will go back to not having the trailing commas as you asked.

**Comment by rafaeelaudibert** [comment]
Hello @arkajyotiMukherjee! If I fix this error, the "Codacy/PR Quality Review" also fails, saying that I need the comma hahahah. Anyways, I will go back to not having the trailing commas as you asked.

**Comment by rafaeelaudibert** [comment]
It looks like you merged another person PR even though I created this one first...

**Pull request closed without merging**
