### PR TITLE
Container kill logo

### PR DESCRIPTION
**Pull request by ven-k**
**This PR adds a new logo for Container kill**:

**This PR solves issue litmuschaos#827**

As instructed in the meetup, a PNG file for the 'Container kill' icon has been added in the 'images' folder, with the file name- **litmus-logo-container_kill.png**.
The palette colors are chosen from the original Litmus logo and both container and the action of killing it is embedded in this logo. I hope creativity in this design gets merged with the master.

### CODE REVIEW

**Comment by harshvkarn** [comment]
I kind of liked it!

**Comment by harshvkarn** [comment]
Instead of png, SVG could be better, IMO.

**Comment by ven-k** [comment]
@harshvkarn thanks for liking my logo design. I've added the svg file of the logo. ( for both container-kill-logo and pod-delete-logo(#873)

**Comment by chandankumar4** [comment]
Thanks for your contribution @ven-k , Can you raise the same PR for Repo (https://github.com/litmuschaos/charthub.litmuschaos.io) and follow the directory structure mention in the issue: https://github.com/litmuschaos/litmus/issues/879, You can close this PR after raising another one.

**Comment by ajeshbaby** [comment]
I am liking this :) Lets hear from designer maintainer @aditya109 / @kalyantt 
 If the format is good for us, we can approve this.

**Comment by ven-k** [comment]
Thank you @chandankumar4 and @ajeshbaby.

I'll add to the #879 of
https://github.com/litmuschaos/charthub.litmuschaos.io by tomorrow morning and close this PR.

**Comment by aditya109** [comment]
Hi @ven-k, we were really impressed by your work in logos. I just have one request. So the icons you have given are to be put for experiments in the [hub](https://hub.litmuschaos.io). Since you have given icons for 2 experiments... can you make the icons for the rest of the experiments as well? It would be great if you actually make for the remaining experiments also.

**Comment by ven-k** [comment]
@aditya109 thank you for liking my logo.
I would be happy to design logos for the other experiments too. Give me 2-3 days, I'll design them.

**Comment by ven-k** [comment]
@chandankumar4 I've created a new PR (litmuschaos/charthub.litmuschaos.io#63) and closing this PR.

**Pull request closed without merging**
