### PR TITLE
(ChaosCenter): Fixed Upgrade Agent

### PR DESCRIPTION
**Pull request by Jonsy13**
Signed-off-by: Jonsy13 <vedant.shrotria@chaosnative.com>

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [X] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [X] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Review by gdsoumya — APPROVED** [review]

**Review by rajdas98 — APPROVED** [review]

**Comment by Jonsy13** [comment]
Hi @lamc , You can ignore that error that is because the version of controlplane in both the charts is same, only version of chart is different due to some changes in chart configs. Upgrade-agent is only concerned with upgrading controlplane from 2.4.0 to 2.5.0.
@gdsoumya can give more details.

**Comment by lamc** [comment]
@Jonsy13 thank you for the quick response, however since I'm automating deployment through spinnaker the deployment fails while waiting for manifest to stabilize with error: `Job has reached the specified backoff limit` I looked at the template and default is 2.  How would you suggest proceeding? I will also wait for more details from @gdsoumya

**Comment by gdsoumya** [comment]
I think it's necessary that the user is notified about the version being the same, you will only run upgrade-agent when you want an upgrade from an older version (it isn't run automatically every time) thus it is important for the user to be notified when a scenario like this occurs where the versions are already same as it is very different from what the user has assumed while running the upgrade-agent. A silent completion in such a case will make this undetectable.

**Comment by lamc** [comment]
@gdsoumya @Jonsy13 thank you it the explanation! this makes sense and I agree that this error notification shouldn't be silenced. For my scenario I will just ignore the failure in my spinnaker pipeline when deploying this helm chart. Thank you so much!! :)

**Pull request merged**
