### PR TITLE
(chaos-center): Added litmus core component version API

### PR DESCRIPTION
**Pull request by amityt**
Signed-off-by: Amit Kumar Das <amit@chaosnative.com>

## Proposed changes

This PR adds:
- envs for Litmus Core Component version
- API for the Litmus Core version (**required in workflow creation**)

Route: `/litmus_core_version`
Response :

> {
coreVersion: "2.7.0"
}

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Review by SarthakJain26 — APPROVED** [review]

**Review by Saranya-jena — APPROVED** [review]

**Review by Jonsy13 — APPROVED** [review]

**Review by Saranya-jena — APPROVED** [review]

**Comment by rajdas98** [comment]
Can we have /version only?

**Comment by rajdas98** [comment]
Just split the image by `:` and use the last element of the array

**Comment by gdsoumya** [comment]
> Can we have /version only?
> 
> and we don't need LITMUS_CORE_VERSION. we can parse it from the CHAOS_OPERATOR/CHAOS_EXPORTER image.

Probably not a good idea, in case we don't have to do a simultaneous release of these images for eg. when no changes are made to the operator then this will not work. Best to have its own version.

**Comment by rajdas98** [comment]
CORE_VERSION and OPERATOR/EXPORTER version will always be same. So, need required to maintain a separate ENV.

**Comment by gdsoumya** [comment]
@amityt is this version anything different from this https://github.com/litmuschaos/litmus/blob/395a4cf2f673fb384017e82e908a41ffb62509b6/litmus-portal/cluster-k8s-manifest.yml#L418 
We already need this for the upgrade agent and it's also being accessed in the server already here https://github.com/litmuschaos/litmus/blob/395a4cf2f673fb384017e82e908a41ffb62509b6/litmus-portal/graphql-server/server.go#L43

I think we can just reuse that, no need for a new version.

**Review by gdsoumya — APPROVED** [review]

**Comment by amityt** [comment]
Hi @rajdas98 @gdsoumya This API is specific to only the workflow related components like runner, k8s etc. As per the user requirement, he/she can update the env and the version will reflect in the workflow manifests.

**Comment by amityt** [comment]
@Jonsy13  We can close this PR. The changes are already added in this PR https://github.com/litmuschaos/litmus/pull/3595

**Comment by Jonsy13** [comment]
Closing this PR as this change is already merged as part of https://github.com/litmuschaos/litmus/pull/3595.

**Pull request closed without merging**
