### PR TITLE
Added version checks in server and agents

### PR DESCRIPTION
**Pull request by gdsoumya**
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>

## Proposed changes

This PR adds the version data in the db and version checks in the server and agent. This PR will form the basis for the upgrade mechanism in the following versions.

Changes:
- New collection to store the version details for the control plane components
- `VERSION` env variable in server and agent
- If server version doesn't match the db version server will not startup
- All requests from the agents are now also checked for version compatibility, if agent is in different version request is denied by the server.

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by rajdas98 — APPROVED** [review]

**Review by ishangupta-ds — APPROVED** [review]
@gdsoumya can we also add the version changes to namespaced manifest template yaml file ? 

Rest looks good !

**Comment by ishangupta-ds** [comment]
@rajdas98 @Jonsy13 does the manifest in docs directory also require this change ? cc: @gdsoumya

**Comment by Jonsy13** [comment]
Yes @gdsoumya Can you pls add this env change in manifests in docs directory too.

**Comment by gdsoumya** [comment]
> Yes @gdsoumya Can you pls add this env change in manifests in docs directory too.

Updated

**Review by Jonsy13 — APPROVED** [review]

**Pull request merged**
