### PR TITLE
(chore)governance: add newer maintainers and reviewers

### PR DESCRIPTION
**Pull request by ksatchit**
Signed-off-by: ksatchit <karthik@chaosnative.com>

## Proposed changes

Updates the governance doc to reflect Github PRs as a way to propose maintainers (there is no dedicated slack channel for maintainers as originally planned. Maintainers like @Jasstkn were added via PR).
 
Changes the role of @ispeakc0de, @rajdas98 & @uditgaurav to maintainers for their awesome contributions to the growth of the litmuschaos project over the past year. 

While @ispeakc0de & @uditgaurav have been instrumental in increasing the experiment suite & the e2e framework, @rajdas98 has been instrumental in the development of the Litmus control plane & orchestration. 

Adds newer reviewers that have contributed significantly over the past year to the various sub-projects within Litmus and continue to build the community! 

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Review by umamukkara — APPROVED** [review]
LGTM

**Review by chandankumar4 — APPROVED** [review]
lgtm

**Comment by ajeshbaby** [comment]
> lgtm

+1

**Comment by k8s-dev** [comment]
LGTM.

Appreciate all the efforts put together by @ispeakc0de @rajdas98 and @uditgaurav for their awesome contributions to make LitmusChaos better!

**Review by Jasstkn — APPROVED** [review]

**Pull request merged**
