### PR TITLE
Fix for Settings route for different users with different roles.

### PR DESCRIPTION
**Pull request by Jonsy13**
Signed-off-by: Vedant Shrotria <vedant.shrotria@mayadata.io>

## Proposed changes

**This PR will fix:**
**- User who is not an owner won't be allowed to go to settings route.**
**- If User who is not an editor or owner of a project is on settings page, will be redirected to homepage while project switching.**

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [X] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [X] I have signed the commit for DCO to be passed.
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Review by Saranya-jena — APPROVED** [review]
LGTM. However, this is a temporary fix as `/settings` route is accessible. @arkajyotiMukherjee Can you review this?

**Comment by arkajyotiMukherjee** [comment]
with this PR the viewer and editor roles can't visit settings page, am I right?
but account settings should be available for all roles if I'm correct
@Jonsy13

**Comment by Jonsy13** [comment]
> with this PR the viewer and editor roles can't visit settings page, am I right?
> but account settings should be available for all roles if I'm correct
> @Jonsy13
 Yes, correct.

**Comment by Saranya-jena** [comment]
@arkajyotiMukherjee Ideally no tabs from settings should be visible if the user is not the Owner of the selected project.

**Comment by arkajyotiMukherjee** [comment]
> @arkajyotiMukherjee Ideally no tabs from settings should be visible if the user is not the Owner of the selected project.

what about account settings...if the user with viewer permission wants to change their name
@Saranya-jena

**Comment by Saranya-jena** [comment]
@arkajyotiMukherjee User then needs to select the project in which he/she is the owner to change the details. This was decided earlier.

**Comment by Jonsy13** [comment]
Yes @Saranya-jena that is current behaviour with this PR.

**Comment by arkajyotiMukherjee** [comment]
Yes yes...thanks for clearing that up...this PR is good then...I'll approve @Jonsy13 @Saranya-jena

**Review by arkajyotiMukherjee — APPROVED** [review]
lgtm

**Pull request merged**
