### PR TITLE
Adding no of workflow and schedules in getCluster query

### PR DESCRIPTION
**Pull request by rajdas98**
## Proposed changes

Adding no of workflow and schedules in getCluster query

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Comment by oumkale** [comment]
@rajdas98 Please will you add mutation for delete cluster as well

**Comment by rjn01** [comment]
@rajdas98 Can you tell me how to do a signed commit

**Comment by rajdas98** [comment]
> @rajdas98 Please will you add mutation for delete cluster as well

Yes, delete cluster mutation can go in a separate PR.

**Comment by rajdas98** [comment]
> @rajdas98 Can you tell me how to do a signed commit

Put -s flag in commit ex- git commit -s -m "msg"

**Review by oumkale — APPROVED** [review]

**Comment by rjn01** [comment]
@rajdas98 I have tried that, but getting this error
error: gpg failed to sign the data
fatal: failed to write commit object

**Comment by rajdas98** [comment]
> @rajdas98 I have tried that, but getting this error
> error: gpg failed to sign the data
> fatal: failed to write commit object

I think your system problem, gpg key is not set properly

**Comment by rajdas98** [comment]
Selection_053

**Comment by rajdas98** [comment]
Merging this PR, Tested it in local

**Comment by oumkale** [comment]
Thank you @rajdas98

**Pull request merged**
