### PR TITLE
Changed install script to skip cypress installation in Dockerfile.

### PR DESCRIPTION
**Pull request by Jonsy13**
Signed-off-by: Vedant Shrotria <vedant.shrotria@mayadata.io>

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

**This PR will add flag "CYPRESS_INSTALL_BINARY=0" to skip Cypress installation.**
**- Tested by building the image myself and applying on kind Cluster.**

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [X] New feature (non-breaking change which adds functionality)
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [X] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [X] I have signed the commit for DCO to be passed.
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

Screenshot from 2020-09-08 20-56-21

### CODE REVIEW

**Comment by Jonsy13** [comment]
Reviewer can test the manifest by applying this --  https://github.com/Jonsy13/litmus/blob/Cypress/litmus-portal/k8s-manifest.yml

**Review by arkajyotiMukherjee — APPROVED** [review]
LGTM

**Comment by rajdas98** [comment]
@Jonsy13 Cypress is still installing
```
> cypress@4.12.0 postinstall /home/circleci/go/src/github.com/litmuschaos/litmus/litmus-portal/frontend/node_modules/cypress
> node index.js --exec install

Installing Cypress (version: 4.12.0)

[14:53:59]  Downloading Cypress     [started]
[14:54:02]  Downloading Cypress     [completed]
[14:54:02]  Unzipping Cypress       [started]
[14:54:11]  Unzipping Cypress       [completed]
[14:54:11]  Finishing Installation  [started]
[14:54:11]  Finishing Installation  [completed]

You can now open Cypress by running: node_modules/.bin/cypress open

https://on.cypress.io/installing-cypress

```

**Comment by rajdas98** [comment]
Please check the circle build

**Pull request merged**
