### PR TITLE
Adding SingleBranch:  true in the git clone options

### PR DESCRIPTION
**Pull request by imrajdas**
Reverts litmuschaos/litmus#3776

### CODE REVIEW

**Review by gdsoumya — CHANGES_REQUESTED** [review]
We should only clone a single branch to reduce unnecessary data being downloaded.
This clone option should force only the required branch data to be cloned : 
```
SingleBranch:  true,
```

**Comment by imrajdas** [comment]
> We should only clone a single branch to reduce unnecessary data being downloaded. This clone option should force only the required branch data to be cloned :
> 
> ```
> SingleBranch:  true,
> ```

@AmitKumarDas - Will it work with the git pull in go-git?

**Comment by gdsoumya** [comment]
> > We should only clone a single branch to reduce unnecessary data being downloaded. This clone option should force only the required branch data to be cloned :
> > ```
> > SingleBranch:  true,
> > ```
> 
> @amityt - Will it work with the git pull in go-git?

It already works and is tested. I did the same with gitops feature ref: https://github.com/litmuschaos/litmus/blob/45693e9b31804a8d6dc3adb4020c57399fe16499/litmus-portal/graphql-server/pkg/gitops/gitops.go#L178

**Review by gdsoumya — APPROVED** [review]

**Comment by gdsoumya** [comment]
@imrajdas LGTM, but lint check and dco is failing, please fix before merging

**Review by Jonsy13 — APPROVED** [review]

**Pull request merged**
