### PR TITLE
Added the GraphQL Schema for Code Generation.

### LINKED ISSUE #1793: Add the GraphQL Schema for Code Generation.
**GraphQL Schema for code generation to be added.**

### PR DESCRIPTION
**Pull request by Jonsy13**
Signed-off-by: Vedant Shrotria <vedant.shrotria@mayadata.io>

**What this PR does / why we need it**: This PR will add Schema for GraphQL API.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1793 

**Checklist**

* [X] Does this PR have a corresponding GitHub issue?
* [ ] Have you included relevant README for the chaoslib/experiment with details?
* [ ] Have you added debug messages where necessary?
* [ ] Have you added task comments where necessary?
* [ ] Have you tested the changes for possible failure conditions?
* [ ] Have you provided the positive & negative test logs for the litmusbook execution?
* [ ] Does the litmusbook ensure idempotency of cluster state?, i.e., is cluster restored to original state?
* [ ] Have you used non-shell/command modules for Kubernetes tasks?
* [ ] Have you (jinja) templatized custom scripts that is run by the litmusbook, if any?
* [ ] Have you (jinja) templatized Kubernetes deployment manifests used by the litmusbook, if any?
* [ ] Have you reused/created util functions instead of repeating tasks in the litmusbook?
* [ ] Do the artifacts follow the appropriate directory structure?
* [ ] Have you isolated storage (eg: OpenEBS) specific implementations, checks?
* [ ] Have you isolated platform (eg: baremetal kubeadm/openshift/aws/gcloud) specific implementations, checks?
* [ ] Are the ansible facts well defined? Is the scope explicitly set for playbook & included utils?
* [ ] Have you ensured minimum/careful usage of shell utilities (awk, grep, sed, cut, xargs etc.,)?
* [ ] Can the limtusbook be executed both from within & outside a container (configurable paths, no hardcode)?
* [ ] Can you suggest the minimal resource requirements for the litmusbook execution?
* [ ] Does the litmusbook job artifact carry comments/default options/range for the ENV tunables?
* [ ] Has the litmusbooks been linted?

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rajdas98** [comment]
Add some description in the Pr

**Comment by rajdas98** [comment]
Add some description in the Pr.
 Are you able to generate the code through this schema?

**Comment by gdsoumya** [comment]
@rajdas98 while generating the resolvers make sure to backup the models in the graph dir. They have modifications for the mongo-db which will be removed on re-generating.

**Comment by Jonsy13** [comment]
@rajdas98 description added.
And yes the code is getting generated through this schema.

**Comment by Jonsy13** [comment]
Screenshot from 2020-07-27 20-16-12

**Comment by Jonsy13** [comment]
Screenshot from 2020-07-27 20-16-29

**Pull request merged**
