### PR TITLE
Converted an extended operation type to a root type in the GraphQL schema

### LINKED ISSUE #4893: GraphQL validation fail with graphql-js
**What happened**:
When I try to build the GraphQL documentation using Spectaql, the build fails during the GraphQL schema validation. I will attach the error trace below.

```
Error: Cannot extend type "Query" because it is not defined.
Cannot extend type "Mutation" because it is not defined. Did you mean "Annotation" or "Invitation"?
Cannot extend type "Subscription" because it is not defined.
Unknown type "Query".
Unknown type "Mutation". Did you mean "Annotation" or "Invitation"?
Unknown type "Subscription".
    at assertValidSDL (/opt/homebrew/lib/node_modules/spectaql/node_modules/graphql/validation/validate.js:135:11)
    at buildASTSchema (/opt/homebrew/lib/node_modules/spectaql/node_modules/graphql/utilities/buildASTSchema.js:44:34)
    at makeExecutableSchema (/opt/homebrew/lib/node_modules/spectaql/node_modules/@graphql-tools/schema/cjs/makeExecutableSchema.js:73:47)
    at loadSchemaFromSDLFile (/opt/homebrew/lib/node_modules/spectaql/dist/spectaql/graphql-loaders.js:112:49)
    at buildSchemas (/opt/homebrew/lib/node_modules/spectaql/dist/spectaql/build-schemas.js:52:47)
    at run (/opt/homebrew/lib/node_modules/spectaql/dist/spectaql/index.js:58:78)
    at loadData (/opt/homebrew/lib/node_modules/spectaql/dist/index.js:566:10)
    at run (/opt/homebrew/lib/node_modules/spectaql/dist/index.js:339:65)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/spectaql/bin/spectaql.js:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1504:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32)
    at Module._load (node:internal/modules/cjs/loader:1098:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:5)
    at node:internal/main/run_main_module:30:49
```

According to the [GraphQL JavaScript documentation](https://github.com/graphql/graphql-js/blob/993d7ce2ee6db2a13973b037817f3eac60607b8a/src/type/schema.ts#L78), a GraphQL schema must include root types (queries, mutations, and subscriptions). Therefore, I suggest changing one of the existing operators in the Chaoscenter GraphQL server schema to a root type.

**What you expected to happen**:
 I expected the GraphQL documentation to build successfully without any validation errors.

**Where can this issue be corrected? (optional)**

It would be good to change the extended operation types in the `chaos_infrastructure.graphqls` file to root types.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install spectaQL. Reference is [here](ref. https://github.com/anvilco/spectaql?tab=readme-ov-file)
```shell
npm install -g spectaql
# OR
yarn global add spectaql
```

2. Generate document with this command.
```shell
npx spectaql config.yml
```

### PR DESCRIPTION
**Pull request by suyeon-jung-dev**
## Proposed changes
I converted an extended operation type to a root type in the GraphQL schema for the following 3 reasons:

1. Initially, this PR included root Query, Mutations, and Subscriptions. [See PR #3602](https://github.com/litmuschaos/litmus/pull/3602).
2.  According to the GraphQL specification, all three operations require root operations to fulfill our intended purposes. [See GraphQL specification](https://spec.graphql.org/October2021/#sec-Root-Operation-Types)

> The **query** root operation type must be provided and must be an Object type.
> 
> The **mutation** root operation type is optional; if it is not provided, the service does not support mutations. If it is provided, it must be an Object type.
> 
> Similarly, the **subscription** root operation type is also optional; if it is not provided, the service does not support subscriptions. If it is provided, it must be an Object type.

  According to the GraphQL specification, a schema must define the root operation types for each kind of operation it supports: queries, mutations, and subscriptions. This implies that there must be a clear starting point for executing any operation in the schema.

3. Also. Without root types, there would be no structured way to initiate queries or mutations, this graphql server could lead to the GraphQL server rendering the schema ineffectively.

I believe this change will ensure that our schema adheres to the GraphQL specifications, potentially improving compatibility and maintainability.

Resolve #4893 

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Comment by Saranya-jena** [comment]
@suyeon-jung-dev can you please confirm if you have tried running the gqlgen command and it's running fine? `go run github.com/99designs/gqlgen generate`

**Comment by suyeon-jung-dev** [comment]
> @suyeon-jung-dev can you please confirm if you have tried running the gqlgen command and it's running fine? `go run github.com/99designs/gqlgen generate`

Hi @Saranya-jena 

The result of running the generate command is as follows.

image

**Comment by suyeon-jung-dev** [comment]
> @suyeon-jung-dev can you please confirm if you have tried running the gqlgen command and it's running fine? `go run github.com/99designs/gqlgen generate`

Hi @Saranya-jena 

I refactored root types to Query and Mutation in chaos_experiment.graphqls to ensure no changes during gqlgen build.

Here is gqlgen generate result.

image

**Comment by suyeon-jung-dev** [comment]
I added generated.go file as well.

And graphql server works well. I attached some logs from graphql server below.

```
{"body_size":116,"client_ip":"::1","error":"","file":"/Users/jeongsuyeon/IdeaProjects/suyeon-jung-dev/litmus/chaoscenter/graphql/server/api/middleware/logger.go:60","func":"main.setupGin.DefaultStructuredLogger.StructuredLogger.func2","latency":"16.802833ms","level":"info","method":"POST","msg":"","path":"/query","status":200,"time":"2024-09-20T21:00:03+09:00"}
{"body_size":90,"client_ip":"::1","error":"","file":"/Users/jeongsuyeon/IdeaProjects/suyeon-jung-dev/litmus/chaoscenter/graphql/server/api/middleware/logger.go:60","func":"main.setupGin.DefaultStructuredLogger.StructuredLogger.func2","latency":"16.807667ms","level":"info","method":"POST","msg":"","path":"/query","status":200,"time":"2024-09-20T21:00:03+09:00"}
{"file":"/Users/jeongsuyeon/IdeaProjects/suyeon-jung-dev/litmus/chaoscenter/graphql/server/graph/environment.resolvers.go:20","func":"github.com/litmuschaos/litmus/chaoscenter/graphql/server/graph.(*mutationResolver).CreateEnvironment","level":"info","msg":"request received to create new environment","projectId":"ef7f1c15-933c-4e2e-a44a-25d62da07649","time":"2024-09-20T21:00:27+09:00"}
{"body_size":259,"client_ip":"::1","error":"","file":"/Users/jeongsuyeon/IdeaProjects/suyeon-jung-dev/litmus/chaoscenter/graphql/server/api/middleware/logger.go:60","func":"main.setupGin.DefaultStructuredLogger.StructuredLogger.func2","latency":"27.907791ms","level":"info","method":"POST","msg":"","path":"/query","status":200,"time":"2024-09-20T21:00:27+09:00"}
{"file":"/Users/jeongsuyeon/IdeaProjects/suyeon-jung-dev/litmus/chaoscenter/graphql/server/graph/environment.resolvers.go:104","func":"github.com/litmuschaos/litmus/chaoscenter/graphql/server/graph.(*queryResolver).ListEnvironments","level":"info","msg":"request received to list environments","projectId":"ef7f1c15-933c-4e2e-a44a-25d62da07649","time":"2024-09-20T21:00:27+09:00"}
{"body_size":458,"client_ip":"::1","error":"","file":"/Users/jeongsuyeon/IdeaProjects/suyeon-jung-dev/litmus/chaoscenter/graphql/server/api/middleware/logger.go:60","func":"main.setupGin.DefaultStructuredLogger.StructuredLogger.func2","latency":"21.589334ms","level":"info","method":"POST","msg":"","path":"/query","status":200,"time":"2024-09-20T21:00:27+09:00"}
```

**Comment by Saranya-jena** [comment]
Awesome thanks for confirming! 🚀

**Review by Saranya-jena — APPROVED** [review]

**Review by namkyu1999 — APPROVED** [review]

**Review by SarthakJain26 — APPROVED** [review]

**Review by Jonsy13 — APPROVED** [review]

**Pull request merged**
