### PR TITLE
update readme.md - typo fixes

### PR DESCRIPTION
**Pull request by Parikshit-Hooda**
**What this PR does / why we need it**:
to fix typos in readme.md file

### typo -> corrected
rerourse -> resource
extention -> extension

Signed-off-by : Parikshit Hooda <phooda804@live.com>

### CODE REVIEW

**Comment by ksatchit** [comment]
Thanks @Parikshit-Hooda ! can you please make signed commits?

**Comment by Parikshit-Hooda** [comment]
@ksatchit If it is possible, please merge it this way only? I have actually included my sign in the commit message. The test will not pass because it wasn't a result of fork-then-fix rather i did it on the github itself.

**Comment by Parikshit-Hooda** [comment]
Also, possibly because the sign is included at the last and not in the first line itself as is the case when I do make signed commits.

**Comment by chandankumar4** [comment]
Without signed commit, I don't think it's possible to merge. If you are facing some difficulties in signing the commit you can follow these steps:
- Clone the forked repo
- Switch to `patch-1` branch
- Merged both commits into a single commit
- Sign the commit using `-s` flag

**Comment by Parikshit-Hooda** [comment]
@chandankumar4 Sure! I shall create another PR within a couple hours.

**Comment by Parikshit-Hooda** [comment]
@chandankumar4 @ksatchit I am closing this PR and opening another that fixes the same issue.

**Pull request closed without merging**
