### PR TITLE
Remove import check from push-pipeline

### PR DESCRIPTION
**Pull request by rajdas98**
Signed-off-by: Raj Das <mail.rajdas@gmail.com>

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Comment by gdsoumya** [comment]
Why is this PR needed? The go-imports check should be present even in the push pipleline too like the backend checks?

**Comment by rajdas98** [comment]
> Why is this PR needed? The go-imports check should be present even in the push pipleline too like the backend checks?

Not required because we are checking it in the build-pipeline first before merging the PR

**Comment by rajdas98** [comment]
push-pipeline will only trigger if code is pushed to master branch and we are not practicing direct commit push

**Comment by gdsoumya** [comment]
Then why are we having the other backend and frontend checks in push
workflow? Those should be removed too. Also I think it's better to have
these checks in push even if it is redundant just for safety.

**Comment by rajdas98** [comment]
> workflow? Those should be removed too. Also I think it's better to have
If it is taking less time, then we can add that checks. Otherwise, we have to remove the other checks also. Just to make the pipeline work, I merged that PR.

**Comment by gdsoumya** [comment]
It takes just 2 seconds https://github.com/litmuschaos/litmus/runs/2271109479?check_suite_focus=true the other backend check rather takes 18 seconds

**Comment by rajdas98** [comment]
> It takes just 2 seconds https://github.com/litmuschaos/litmus/runs/2271109479?check_suite_focus=true the other backend check rather takes 18 seconds

I meant we have to remove all checks, it is taking more that 3 mins

**Comment by specter25** [comment]
@rajdas98 sir  should i remove the backend checks from the puh pipeline then ?

**Comment by rajdas98** [comment]
> @rajdas98 sir should i remove the backend checks from the push pipeline then ?

Yes please

**Comment by specter25** [comment]
okay so should i create a issue as well?

**Comment by specter25** [comment]
@rajdas98 should we remove the frontend checks as well from the push pipeline , as they are being executed in the build pipeline ?

**Comment by rajdas98** [comment]
> @rajdas98 should we remove the frontend checks as well from the push pipeline , as they are being executed in the build pipeline ?

Yes, frontend checks too, and also Can you add golangci-lint action(For this, you might need to solve some lint issues in the litmus codebase)?

**Comment by specter25** [comment]
Okay sir sure I will do the tasks asap

**Pull request closed without merging**
