### PR TITLE
fix ususual space around project selection card

### LINKED ISSUE #4675: Unusual space between projects in project selection screen
**What happened**:
There's excessive space around the project cards, making the layout appear inconsistent
Screenshot from 2024-05-27 22-00-05

**What you expected to happen**:
Minimal necessary space should be maintained between project cards to enhance the user experience.

**How to reproduce it (as minimally and precisely as possible)**:
Create 3 projects.
Go to the project selection screen.
Notice the spacing around the project cards

### PR DESCRIPTION
**Pull request by JanhaviAlekar**
fixes #4675
## Proposed changes
Enhancing user experience by removing unusual space around project selection card 
results :
Screenshot from 2024-05-27 20-22-57

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by hrishavjha — APPROVED** [review]
We can remove this class, not necessary but because `flex-grow: 0` is a default value.

**Comment by JanhaviAlekar** [comment]
> We can remove this class, not necessary but because `flex-grow: 0` is a default value.

Removed it

**Review by namkyu1999 — APPROVED** [review]

**Review by amityt — APPROVED** [review]

**Comment by Saranya-jena** [comment]
@JanhaviAlekar can you resolve the conflicts? We can merge it afterwards.

**Comment by JanhaviAlekar** [comment]
> @JanhaviAlekar can you resolve the conflicts? We can merge it afterwards.

Done

**Pull request merged**
