### PR TITLE
Updating run.sh in the Litmus-portal

### PR DESCRIPTION
**Pull request by kitarp29**
## Proposed changes

As talked with @rajdas98 the shell script was not well managed. Updating the fix for the issues I faced in running the script
Doc: [Here](https://stackoverflow.com/questions/15573679/unary-operator-expected-in-shell-script-when-comparing-null-value-with-string)

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Comment by kitarp29** [comment]
@rajdas98 @Jonsy13 
Can someone check and tell me the fix for Code refactor in this?

**Comment by rajdas98** [comment]
@kitarp29 the script is working fine before, we are missing some envs in this script.

 @Jonsy13  can you confirm it?

**Comment by Jonsy13** [comment]
**Hi @kitarp29 , I just tested it, The Script is working fine.**
- `bash run.sh gql`
- `bash run.sh auth`
- `npm start`

**Comment by kitarp29** [comment]
Hey @Jonsy13 
the gql command is still running into error for me.
IDK the issue, but the fix looked like a syntax error in bash script

**Comment by rajdas98** [comment]
As the script is running fine closing this PR. Maybe the system related issue.

**Pull request closed without merging**
