### PR TITLE
Fix failing CI tests and remove go imports check from push.yml

### PR DESCRIPTION
**Pull request by specter25**
## Proposed changes

- Fix failing CI tests
- Remove go imports check from push.yml
- This change was requested in #2632 

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Comment by specter25** [comment]
@rajdas98 sir I have fixed  failing CI test and removed the go-imports check in the push.yml pipeline as you requested in #2632 .

**Comment by specter25** [comment]
@rajdas98  sir , do I have to create a new issue for it as well?

**Review by rajdas98 — APPROVED** [review]

**Comment by rajdas98** [comment]
Not required. I have merged it.

**Comment by gdsoumya** [comment]
@rajdas98 same question as https://github.com/litmuschaos/litmus/pull/2640#issuecomment-813494443

**Comment by rajdas98** [comment]
> @rajdas98 same question as [#2640 (comment)](https://github.com/litmuschaos/litmus/pull/2640#issuecomment-813494443)

https://github.com/litmuschaos/litmus/pull/2640#issuecomment-813527145
https://github.com/litmuschaos/litmus/pull/2640#issuecomment-813528388

**Pull request merged**
