### PR TITLE
Alter email to base64, because the regex enconding

### PR DESCRIPTION
**Pull request by deividMatos**
## Proposed changes

Changed the user email to base64 for the k8s labels objects, regarding to this [issue](https://github.com/litmuschaos/litmus/issues/3634). #3634 
This was implemented based on this [comment](https://github.com/litmuschaos/litmus/pull/3648#issuecomment-1192535846) for PR #3648.

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Review by imrajdas — APPROVED** [review]

**Comment by imrajdas** [comment]
Thanks, @deividMatos for this PR. 

One quest- Have you tested it in your local dev?

**Comment by deividMatos** [comment]
> Thanks, @deividMatos for this PR.
> 
> One quest- Have you tested it in your local dev?

Yes, I tested it with a member of my squad and we created several flows to test in different scenarios, all in local dev

**Review by Jonsy13 — APPROVED** [review]

**Comment by amityt** [comment]
Thanks @deividMatos for this PR! This will unblock a lot of users! Have test the changes and will take it as part of our next release! 🚀

**Comment by ludovic-pourrat** [comment]
Thanks @deividMatos works for us too !

**Comment by ludovic-pourrat** [comment]
Hi,

Could we decode this in the UI to display the originating user email ?

**Comment by amityt** [comment]
Hi @ludovic-pourrat , this is already handled in the UI. Attaching a screenshot for reference!
Screenshot 2022-08-17 at 6 56 32 PM

**Comment by ludovic-pourrat** [comment]
@amityt my bad my graphql-server was not updated, after applying the patch on my deployment, many thanks for your answer !

**Pull request merged**
