### PR TITLE
fixed main-nav height

### LINKED ISSUE #4419: Add `dashboard` button in side menu in the chaoscenter
In account settings page, there is no button to go to `dashboard`.
User has to manually navigate to '/' path.
We can add a `dashboard` button in side menu shown below.
image
I am willing to make PR regarding this.

### PR DESCRIPTION
**Pull request by milinddethe15**
Closes #4419 
## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:
After the changes:
https://github.com/litmuschaos/litmus/assets/99114125/347ea8d4-79e6-4a2c-877d-fcbc0c16be20

### CODE REVIEW

**Review by hrishavjha — APPROVED** [review]

**Comment by namkyu1999** [comment]
Hi @milinddethe15 , please check DCO :)

**Comment by milinddethe15** [comment]
i am unsure how to fix DCO. 
It shows "Commit sha: [6efb8d9](https://github.com/litmuschaos/litmus/pull/4472/commits/6efb8d9909cc7a974f3eb863b0e11ac74dac4f9a), Author: M!l!nd, Committer: GitHub; Expected "M!l!nd [99114125+milinddethe15@users.noreply.github.com](mailto:99114125+milinddethe15@users.noreply.github.com)", but got "M!l!nd [99114125+milinddethe15@users.noreply.github.com](mailto:99114125+milinddethe15@users.noreply.github.com)"."

**Review by SahilKr24 — APPROVED** [review]
Thanks for the fix. Looks good, please attach a short before and after video for quick visualisation.

**Comment by SahilKr24** [comment]
> i am unsure how to fix DCO. It shows "Commit sha: [6efb8d9](https://github.com/litmuschaos/litmus/pull/4472/commits/6efb8d9909cc7a974f3eb863b0e11ac74dac4f9a), Author: M!l!nd, Committer: GitHub; Expected "M!l!nd [99114125+milinddethe15@users.noreply.github.com](mailto:99114125+milinddethe15@users.noreply.github.com)", but got "M!l!nd [99114125+milinddethe15@users.noreply.github.com](mailto:99114125+milinddethe15@users.noreply.github.com)"."

I think the issue might be because of `!` in the name. Maybe you can use `i` and test it out, we will manually set it to pass for this one.

**Review by arkajyotiMukherjee — APPROVED** [review]

**Comment by milinddethe15** [comment]
before: https://github.com/litmuschaos/litmus/issues/4419#issuecomment-1952328248
after: https://github.com/litmuschaos/litmus/assets/99114125/347ea8d4-79e6-4a2c-877d-fcbc0c16be20 (already mentioned in pr comment)

**Pull request merged**
