### PR TITLE
Image registry bug fix

### PR DESCRIPTION
**Pull request by aditya3103**
## Proposed changes

Image Registry value was not being fetched and reflected in the chaos studio yaml section, it was always overriding and applying the default image registry values

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Comment by aditya3103** [comment]
DCO is correctly signed, used my real name instead of GitHub username

**Review by amityt — APPROVED** [review]

**Comment by imrajdas** [comment]
Thanks @aditya3103 for this PR , the github pipelines are running now.

**Comment by aditya3103** [comment]
I have rectified the import order which was resulting in an error in the frontend build pipeline @imrajdas

**Comment by aditya3103** [comment]
Should I also fix the warnings from the Codacy Static Code Analysis ?

**Comment by amityt** [comment]
> Should I also fix the warnings from the Codacy Static Code Analysis ? @amityt @imrajdas @namkyu1999

Sure @aditya3103 , just checked the codacy review, those are some minor change, will be good if you can add them. Thanks! 🙌🏼

**Comment by aditya3103** [comment]
> > Should I also fix the warnings from the Codacy Static Code Analysis ? @amityt @imrajdas @namkyu1999
> 
> Sure @aditya3103 , just checked the codacy review, those are some minor change, will be good if you can add them. Thanks! 🙌🏼

I have fixed all the warning from codacy, hope it is merge-worthy now !

**Review by Saranya-jena — APPROVED** [review]

**Review by hrishavjha — APPROVED** [review]

**Pull request merged**
