### PR TITLE
feat: change manifests folder chown grp to 0(root) - openshift friendly

### PR DESCRIPTION
**Pull request by tuananh**
Signed-off-by: Tuan Anh Tran <me@tuananh.org>

## Proposed changes

Change manifests folder chown grp to 0(root) group to make it openshift friendly.

require this PR to be merged first https://github.com/litmuschaos/test-tools/pull/200

Openshift run container with an arbitrary uid that in the root group. we want that arbitrary container user to have full access to /litmus so we can change the permission of the folder in /litmus to be litmus:0 (edited)

it's similar with what nginx-unprivileged is doing as well nginxinc/docker-nginx-unprivileged#10

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

require this PR to be merged first https://github.com/litmuschaos/test-tools/pull/200

### CODE REVIEW

**Comment by tuananh** [comment]
hadolint fails but it seems to be fixed upstream https://github.com/hadolint/hadolint/issues/609

**Review by Jonsy13 — APPROVED** [review]

**Review by oumkale — APPROVED** [review]

**Review by rajdas98 — CHANGES_REQUESTED** [review]
One PR check is failing.

**Comment by rajdas98** [comment]
@tuananh Can you update your branch?

**Comment by tuananh** [comment]
@rajdas98 updated :)

**Review by rajdas98 — APPROVED** [review]
LGTM. Thanks @tuananh

**Pull request merged**
