### PR TITLE
Feat: Tests cases for Chaoscenter Rest handler in Chaoscenter

### PR DESCRIPTION
**Pull request by Freedisch**
## Proposed changes

This PR add test cases for Chaoscenter authentication Rest handler

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Comment by namkyu1999** [comment]
Can you resolve conflicts?

**Comment by Freedisch** [comment]
> Can you resolve conflicts?

Done

**Comment by Freedisch** [comment]
image

**Review by namkyu1999 — CHANGES_REQUESTED** [review]
Test failed, Can you check @Freedisch ?
Screenshot 2023-11-30 at 9 14 02 PM

**Review by namkyu1999 — COMMENTED** [review]
LGTM 🚀 @Freedisch, Can you add more test cases in each unit test? In most unit tests, there is only one test case. Checking code coverage will help you figure out which cases you need to add.

**Review by vanshBhatia-A4k9 — APPROVED** [review]
Thank you for inproving the test suite.
Also please address the review comments left by @namkyu1999

**Comment by Freedisch** [comment]
> Thank you for inproving the test suite. Also please address the review comments left by @namkyu1999

Sure I'm working on it

**Review by amityt — APPROVED** [review]

**Review by namkyu1999 — CHANGES_REQUESTED** [review]
Can you check failed cases? I will approve this pr when you fix it 🚀

Screenshot 2023-12-11 at 4 18 16 PM

**Comment by Freedisch** [comment]
@namkyu1999, I just finished fixing the falling test and added a few ones

**Review by namkyu1999 — APPROVED** [review]
LGTM🚀

**Pull request merged**
