### PR TITLE
feat: auto import prometheus datasource and dashboard in grafana deployment

### LINKED ISSUE #2476: Improve deployment of chaos interleaved grafana dashboards
Currently, we have to import the grafana dashboard and connect the data source manually. 
Instead, we can put in a ConfigMap and mount it in Grafana's deployment. It will automatically connect  to the data source and import the dashboards

ref- https://github.com/litmuschaos/litmus/tree/master/monitoring

### PR DESCRIPTION
**Pull request by DarthBenro008**
## Proposed changes

- Fixes #2476
- Added respective config maps
- Added a provisioner for grafana dashboard imports are specified in the [Grafana Documentation](https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards)
- Updated the node-and-pod-metrics.json file as it was giving and issue as described [here](https://github.com/grafana/grafana/issues/10786) and implemented a solution described [here](https://github.com/grafana/grafana/issues/11018#issuecomment-368472235)
- Updated the readme to let the user the user know that the dashboard and datasource are automatically imported.

Datasource automatically imported during deployment:
datasource

Dashboard automatically imported under services folder:
node_metrics

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [X] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [X] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [X] I have signed the commit for DCO to be passed.
- [X] Lint and unit tests pass locally with my changes
- [X] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [X] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Review by ishangupta-ds — COMMENTED** [review]
@DarthBenro008 have you checked for all existing dashboards in grafana-dashboards folder?

**Comment by DarthBenro008** [comment]
@ishangupta-ds No, I apologise I missed to mention this in the PR description, modifying the `Node-and-pod-metrics-dashboard.json` felt sceptical, hence I opened this PR as a proof that it works this way and for proving I started out with node and pod metrics.

Should I automatically import the other grafana-dashboards under the service folder too?

Note: There might be modifications in those json files too.

**Comment by ishangupta-ds** [comment]
> @ishangupta-ds No, I apologise I missed to mention this in the PR description, modifying the `Node-and-pod-metrics-dashboard.json` felt sceptical, hence I opened this PR as a proof that it works this way and for proving I started out with node and pod metrics.
> 
> Should I automatically import the other grafana-dashboards under the service folder too?
> 
> Note: There might be modifications in those json files too.

yes @DarthBenro008 you can modify them as well.

**Comment by DarthBenro008** [comment]
Okay, thank you for the confirmation @ishangupta-ds. I will look into them and add it!

**Comment by DarthBenro008** [comment]
@ishangupta-ds I think it would be a good idea to move the configmaps of dashboards as well as the provisioner to a new file named `dashboard-configmaps.yaml`  or something similar, this would provide a much cleaner structure than dumping all the configmaps inside `deployment.yaml`. What do you suggest?

**Comment by ishangupta-ds** [comment]
> @ishangupta-ds I think it would be a good idea to move the configmaps of dashboards as well as the provisioner to a new file named `dashboard-configmaps.yaml` or something similar, this would provide a much cleaner structure than dumping all the configmaps inside `deployment.yaml`. What do you suggest?

Yes @DarthBenro008 it would be better that way, please go ahead and create two separate configmap files, one for data source and one for dashboards. Also add a README to the grafana folder with short descriptions of each file and also listing the data source and dashboards which are being auto configured. Mention the names too.

**Comment by DarthBenro008** [comment]
Hey @ishangupta-ds , I have made the requested changes and updated the Readme inside the grafana folder too!

**Review by ishangupta-ds — APPROVED** [review]
LGTM

**Comment by DarthBenro008** [comment]
@ishangupta-ds @rajdas98 The CI is failing at Markdown checks, may I know which markdown style guide should I follow and are there any plugins for nvim/VSC for the same?

**Review by rajdas98 — APPROVED** [review]

**Comment by rajdas98** [comment]
Thanks @DarthBenro008

**Pull request merged**
