### PR TITLE
Change fatal error to standard error for some logs

### PR DESCRIPTION
**Pull request by rajdas98**
Signed-off-by: rajdas98 <mail.rajdas@gmail.com>

## Proposed changes

fixes- https://github.com/litmuschaos/litmus/issues/3245#issuecomment-997934195

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Review by Jonsy13 — APPROVED** [review]

**Comment by gdsoumya** [comment]
Some of these need to be fatal errors, the logs were fatal deliberately because if the cluster connect has failed nothing else should be working on the subscriber. Please revert the changes @rajdas98

**Comment by rajdas98** [comment]
> Some of these need to be fatal errors, the logs were fatal deliberately because if the cluster connect has failed nothing else should be working on the subscriber. Please revert the changes @rajdas98

@gdsoumya Cluster dail's error is in fatal- https://github.com/rajdas98/litmus/blob/e1edf723bc2d6c577cdbd7a5a8bd0513e05cd478/litmus-portal/cluster-agents/subscriber/pkg/requests/webhook.go#L33

**Comment by gdsoumya** [comment]
everything inside the go function needs to be fatal, everything apart from the ReadMessage call in the loop can be errors but they need a continue statement after the log message.

**Comment by rajdas98** [comment]
> @rajdas98 everything inside the go function needs to be fatal, everything apart from the ReadMessage call in the loop can be errors but they need a continue statement after the log message.

doesn't matter because we are not getting the payload data from the user. It's hardcoded.

**Comment by rajdas98** [comment]
subscriber performs other activities such as sending events, logs through mutution. if we give fatal for WebSocket connection failure, then the other functionalities will stall.

**Comment by gdsoumya** [comment]
That is necessary, this is how the subscriber was designed. The events and logs are pretty useless without the actual cluster connect, no one can ask for logs or k8s objects without the portal to cluster connection. The events will also cause issues because if the server is down or lost connectivity all the events sent will be lost, this was also a major reason for the restarts so that the subscriber when it connects fetches all the missed events and sends them to the portal.

**Comment by rajdas98** [comment]
I know, I was thinking during the runtime of the subscriber, if the subscription has any issues, then we should run the other mutations because both mutation and subscription use different protocols. In some cases where WS protocol got blocked during the runtime and HTTP was running.

But I got your point, Will revert it soon.

**Pull request merged**
