### PR TITLE
chore(litmus-portal): added title image , fixed a link & few typos

### PR DESCRIPTION
**Pull request by xmonish**
## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [ ] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Review by S-ayanide — APPROVED** [review]

**Comment by S-ayanide** [comment]
Thanks for sending in a PR 🎉 

Can you please Sign you commit! We value DCO and would like it if you could sign it.

**Review by arkajyotiMukherjee — APPROVED** [review]
Thanks for contributing to litmuschaos

**Review by ishangupta-ds — APPROVED** [review]

**Comment by prithvi1307** [comment]
@xmonish Please drop in your email id for us to send you your swag!

**Comment by xmonish** [comment]
> @xmonish Please drop in your email id for us to send you your swag!

My email id is monishsingh26@gmail.com
Thanks!

**Pull request merged**
