### PR TITLE
data-cy, invitation bug fix, Role visibility in manage team

### PR DESCRIPTION
**Pull request by A4k9**
Signed-off-by: Vansh Bhatia <vansh.bhatia@mayadata.io>

## Proposed changes

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue

- Added "data-cy" tags required for the latest Cypress tests 
- fixed a bug in the invitation section described below:

When no project is selected (known bug, no fix yet):

Screenshot from 2020-10-12 23-00-45

The invitation/received tab crashes:

Screenshot from 2020-10-12 23-00-50

Added a check to avoid this

- Added the role being invited for in the invitation/received

Screenshot from 2020-10-13 00-51-06

 
## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Review by Saranya-jena — APPROVED** [review]
LGTM @arkajyotiMukherjee Can you suggest some design improvements in the received invitation section? Currently, we don't have the design to display the role.

**Comment by arkajyotiMukherjee** [comment]
> LGTM @arkajyotiMukherjee Can you suggest some design improvements in the received invitation section? Currently, we don't have the design to display the role.

Where do you want to display the role exactly...can you mention in a screenshot @Saranya-jena

**Comment by Saranya-jena** [comment]
Screenshot from 2020-10-13 01-06-40
Here we have displayed the role in brackets

**Review by Jonsy13 — DISMISSED** [review]

**Comment by A4k9** [comment]
- Disabled the "Connect the target" button for Viewers, added tool tip to show "Insufficient Permissions"

Screenshot from 2020-10-13 15-14-40

**Review by Saranya-jena — APPROVED** [review]

**Review by amityt — APPROVED** [review]

**Review by ishangupta-ds — APPROVED** [review]

**Pull request merged**
